{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Last30Days_WithCapacityFilter\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.141.1253.0 (25.03)+74f9999a1e95f78c739f3ea2b96ba340e9ba8729"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-GB",
    "cultures": [
      {
        "name": "en-GB",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "Last30Days_WithCapacityFilter",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CAPACITYNAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9fe1fa9-6c8f-4ea3-b7f9-1d869ed73a1b",
            "sourceColumn": "CAPACITYNAME",
            "summarizeBy": "none"
          },
          {
            "name": "WORKSPACENAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2afbd935-effa-4c5a-abaa-96484129c7bb",
            "sourceColumn": "WORKSPACENAME",
            "summarizeBy": "none"
          },
          {
            "name": "ACTIVITY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "01d0f159-2099-4374-800e-ee5cc73599f5",
            "sourceColumn": "ACTIVITY",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "59903a0f-16ab-41da-9d6d-4dfeb2f0c385",
        "partitions": [
          {
            "name": "Last30Days_WithCapacityFilter",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"C:\\Users\\S.Talari2\\OneDrive - Entain Group\\Desktop\\Personal Workspaces\\PersonalWorkspaces_Check - Last 30 days - With CapID Filter.xlsx\"), null, true),",
                "    Last30Days_WithCapacityFilter_Sheet = Source{[Item=\"Last30Days_WithCapacityFilter\",Kind=\"Sheet\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Last30Days_WithCapacityFilter_Sheet,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}}),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Changed Type\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"CAPACITYNAME\", type text}, {\"WORKSPACENAME\", type text}, {\"ACTIVITY\", type text}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}