createOrReplace

	table 'Dataset for github'
		lineageTag: c43d6756-a344-4da1-b4cf-c03b886974d5

		column WorkspaceId
			dataType: string
			lineageTag: 783c1b7e-762e-435f-b012-d448cca8ced7
			summarizeBy: none
			sourceColumn: WorkspaceId

			annotation SummarizationSetBy = Automatic

		column ItemId
			dataType: string
			lineageTag: a253eb3b-4930-4693-b28d-ddcf75e5e335
			summarizeBy: none
			sourceColumn: ItemId

			annotation SummarizationSetBy = Automatic

		partition 'Dataset for github' = m
			mode: import
			source =
					let
					    Csv.Document(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/Documentation/Test_incremental/Dataset%20for%20github.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
					    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
					    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
					    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"WorkspaceId", type text}, {"ItemId", type text}})
					in
					    #"Changed Type1"

		annotation PBI_NavigationStepName = Navigation

		annotation PBI_ResultType = Table

