table DimDate
	lineageTag: 63c54ed1-ad4d-4162-97c5-b9a6dd175a91
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		formatString: dd/mm/yyyy
		lineageTag: 3e43c4eb-af33-499d-bf28-de84c7da80b4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: b7c8c8ae-a469-485c-b58b-8fb206fcffa1
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Quarter Num'
		dataType: int64
		formatString: 0
		lineageTag: a6096875-6867-4cf9-bacb-e8dbebe03173
		summarizeBy: none
		sourceColumn: Quarter Num

		annotation SummarizationSetBy = Automatic

	column 'Quarter Year'
		dataType: string
		lineageTag: 3a65d429-bc47-449a-9f10-12ca45d47899
		summarizeBy: none
		sourceColumn: Quarter Year

		annotation SummarizationSetBy = Automatic

	column 'Quarter Year Order'
		dataType: int64
		formatString: 0
		lineageTag: 89d6d216-7ade-41a5-850f-824ba008367f
		summarizeBy: none
		sourceColumn: Quarter Year Order

		annotation SummarizationSetBy = Automatic

	column 'Month Num'
		dataType: int64
		formatString: 0
		lineageTag: e5768a5e-853a-42b2-8a51-7ca908a13396
		summarizeBy: none
		sourceColumn: Month Num

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 3fa36e07-85eb-4041-a400-df1bd1774c69
		summarizeBy: none
		sourceColumn: Month Name
		sortByColumn: 'Month Num'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Month Name Short'
		dataType: string
		lineageTag: 701fb907-2659-46a7-beb7-e4d861b6064f
		summarizeBy: none
		sourceColumn: Month Name Short

		annotation SummarizationSetBy = Automatic

	column 'Month Year'
		dataType: string
		lineageTag: f66648f1-5bbe-41d3-9a93-acf430710ce6
		summarizeBy: none
		sourceColumn: Month Year

		annotation SummarizationSetBy = Automatic

	column 'Month Year Order'
		dataType: int64
		formatString: 0
		lineageTag: 0b04efc0-06d8-4ee4-aa9d-28cf21e8dec7
		summarizeBy: none
		sourceColumn: Month Year Order

		annotation SummarizationSetBy = Automatic

	column 'Month Day Num'
		dataType: int64
		formatString: 0
		lineageTag: ba22ce1f-7b0a-4735-a622-4dac909ed855
		summarizeBy: none
		sourceColumn: Month Day Num

		annotation SummarizationSetBy = Automatic

	column 'Date Int'
		dataType: int64
		formatString: 0
		lineageTag: 63e69ff4-9acf-4d8e-ae59-91654c94d379
		summarizeBy: none
		sourceColumn: Date Int

		annotation SummarizationSetBy = Automatic

	column 'Day Month'
		dataType: string
		lineageTag: 3662abc2-5b93-4e29-b896-34fd98940e30
		summarizeBy: none
		sourceColumn: Day Month

		annotation SummarizationSetBy = Automatic

	column 'Day Month Order'
		dataType: int64
		formatString: 0
		lineageTag: f74b82f6-56e3-4a5e-80c2-43b0fc5be6da
		summarizeBy: none
		sourceColumn: Day Month Order

		annotation SummarizationSetBy = Automatic

	column 'Week Num'
		dataType: int64
		formatString: 0
		lineageTag: d2697382-bc48-42e7-9e45-3f99dda81dcb
		summarizeBy: none
		sourceColumn: Week Num

		annotation SummarizationSetBy = Automatic

	column 'Week Year'
		dataType: string
		lineageTag: 1ada1513-38e9-49bd-aea3-2df9af7d6e75
		summarizeBy: none
		sourceColumn: Week Year

		annotation SummarizationSetBy = Automatic

	column 'Week Year Order'
		dataType: int64
		formatString: 0
		lineageTag: 014e3b4a-4380-4d5d-86dc-a3d496b0807a
		summarizeBy: none
		sourceColumn: Week Year Order

		annotation SummarizationSetBy = Automatic

	column 'Week Starting'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0f9e5444-1251-46c2-8b70-3d798ac364ea
		summarizeBy: none
		sourceColumn: Week Starting

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Week Ending'
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac794dfc-215d-4051-9270-01a250b8afe7
		summarizeBy: none
		sourceColumn: Week Ending

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Starting'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6b4ecf93-9571-4e48-bf20-832834ae93aa
		summarizeBy: none
		sourceColumn: Month Starting

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Ending'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 76879585-a8f2-450d-a2a2-a0ce1f76f0ac
		summarizeBy: none
		sourceColumn: Month Ending

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Quarter Starting'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2b033c23-ed23-49b8-a592-674fd1b96972
		summarizeBy: none
		sourceColumn: Quarter Starting

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Quarter Ending'
		dataType: dateTime
		formatString: Long Date
		lineageTag: f1a9e791-a8cf-4b74-89cb-133e6ac73f4a
		summarizeBy: none
		sourceColumn: Quarter Ending

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Year Starting'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8dd2fa5d-e5a0-4bb3-83a2-29969b782bb0
		summarizeBy: none
		sourceColumn: Year Starting

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Year Ending'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f7aab4c-c4ed-47b3-bd1a-503bd63edee2
		summarizeBy: none
		sourceColumn: Year Ending

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Day Num Week'
		dataType: int64
		formatString: 0
		lineageTag: 50d52b84-3ece-45fe-9768-4c4cb4c7e2b6
		summarizeBy: none
		sourceColumn: Day Num Week

		annotation SummarizationSetBy = Automatic

	column 'Day Name'
		dataType: string
		lineageTag: 9ded3f91-14ab-4bda-b1bd-711a938cf357
		summarizeBy: none
		sourceColumn: Day Name
		sortByColumn: 'Day Num Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Weekend
		dataType: int64
		formatString: 0
		lineageTag: f345ac8a-8736-4fa8-aa39-6393aa29396c
		summarizeBy: none
		sourceColumn: Weekend

		annotation SummarizationSetBy = Automatic

	column 'Day Name Short'
		dataType: string
		lineageTag: aa91e4f1-f2bb-4375-bf8b-3a81ea89da98
		summarizeBy: none
		sourceColumn: Day Name Short
		sortByColumn: 'Day Num Week'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 0773f9b0-1961-4279-ab69-6a0a44756c24
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column 'Day of Year'
		dataType: int64
		formatString: 0
		lineageTag: 6df3c231-ddda-4324-873a-ee82df721f9a
		summarizeBy: none
		sourceColumn: Day of Year

		annotation SummarizationSetBy = Automatic

	column Yesterday?
		dataType: int64
		formatString: 0
		lineageTag: ddaf67bd-e004-467f-bbb9-691b6872e81d
		summarizeBy: none
		sourceColumn: Yesterday?

		annotation SummarizationSetBy = Automatic

	column L7Days?
		dataType: int64
		formatString: 0
		lineageTag: 6afe025e-c244-413d-8b28-b84ed0b3b71a
		summarizeBy: none
		sourceColumn: L7Days?

		annotation SummarizationSetBy = Automatic

	column 'Current Day?'
		dataType: int64
		formatString: 0
		lineageTag: 9f9d9d84-3735-4e6d-973e-997d1f99771a
		summarizeBy: none
		sourceColumn: Current Day?

		annotation SummarizationSetBy = Automatic

	column 'Current Week?'
		dataType: int64
		formatString: 0
		lineageTag: 198232f9-1724-4ca4-8a97-8961dbbe4404
		summarizeBy: none
		sourceColumn: Current Week?

		annotation SummarizationSetBy = Automatic

	column 'Current Month?'
		dataType: int64
		formatString: 0
		lineageTag: 499f1cc0-0f2a-4a75-b3fd-4d9bb58cabbf
		summarizeBy: none
		sourceColumn: Current Month?

		annotation SummarizationSetBy = Automatic

	column 'Current Quarter?'
		dataType: int64
		formatString: 0
		lineageTag: a1163c6e-75de-4ce4-87f3-b88a4293948e
		summarizeBy: none
		sourceColumn: Current Quarter?

		annotation SummarizationSetBy = Automatic

	column 'Current Year?'
		dataType: int64
		formatString: 0
		lineageTag: 77cace30-4d0d-472e-bf3f-d222f985acf0
		summarizeBy: none
		sourceColumn: Current Year?

		annotation SummarizationSetBy = Automatic

	column 'Completed Days'
		dataType: int64
		formatString: 0
		lineageTag: d45c784a-0f77-4863-aae3-f99433ee15d7
		summarizeBy: none
		sourceColumn: Completed Days

		annotation SummarizationSetBy = Automatic

	column 'Completed Weeks'
		dataType: int64
		formatString: 0
		lineageTag: d5d64d37-4a1c-4d48-9e7a-df9fedaa322e
		summarizeBy: none
		sourceColumn: Completed Weeks

		annotation SummarizationSetBy = Automatic

	column 'Completed Months'
		dataType: int64
		formatString: 0
		lineageTag: bba1e242-6dcd-49df-9076-9c7b308de038
		summarizeBy: none
		sourceColumn: Completed Months

		annotation SummarizationSetBy = Automatic

	column 'Completed Quarters'
		dataType: int64
		formatString: 0
		lineageTag: fec80663-d55b-45a3-ae1e-0da35c15217d
		summarizeBy: none
		sourceColumn: Completed Quarters

		annotation SummarizationSetBy = Automatic

	column 'Completed Years'
		dataType: int64
		formatString: 0
		lineageTag: fd731e03-e541-45f0-8dee-3ed2c3906a2b
		summarizeBy: none
		sourceColumn: Completed Years

		annotation SummarizationSetBy = Automatic

	column YearsFromActualYear
		dataType: int64
		formatString: 0
		lineageTag: 63aba837-f6a6-4f37-b39d-cdd9f03cf8eb
		summarizeBy: none
		sourceColumn: YearsFromActualYear

		annotation SummarizationSetBy = Automatic

	column QuartersFromActualQuarter
		dataType: int64
		formatString: 0
		lineageTag: 3f0c35ae-64e3-4490-88d8-a9e3e95b738f
		summarizeBy: none
		sourceColumn: QuartersFromActualQuarter

		annotation SummarizationSetBy = Automatic

	column MonthsFromActualMonth
		dataType: int64
		formatString: 0
		lineageTag: 64d8e4a5-2a40-4056-bfa1-e050364fafaf
		summarizeBy: none
		sourceColumn: MonthsFromActualMonth

		annotation SummarizationSetBy = Automatic

	column DaysFromToday
		dataType: int64
		formatString: 0
		lineageTag: eddc916e-e15e-4290-a0a0-4db3f1d8a65a
		summarizeBy: none
		sourceColumn: DaysFromToday

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Month Num'
		dataType: int64
		formatString: 0
		lineageTag: dfd9ee33-d1a2-4142-be71-ed130662e95d
		summarizeBy: none
		sourceColumn: Fiscal Month Num

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter Num'
		dataType: int64
		formatString: 0
		lineageTag: 06ec76c6-8ac4-42bb-bb9a-ea6840d2b581
		summarizeBy: none
		sourceColumn: Fiscal Quarter Num

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 548ff11d-95c4-4bde-8943-56cbda0a0bae
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year Num'
		dataType: int64
		formatString: 0
		lineageTag: c8317e0d-90b0-41dd-8897-ba07c8b91bf2
		summarizeBy: none
		sourceColumn: Fiscal Year Num

		annotation SummarizationSetBy = Automatic

	column 'Fiscal MM-YYYY'
		dataType: string
		lineageTag: d82deb53-a5d6-4c56-8175-bf6a8d5c8b03
		summarizeBy: none
		sourceColumn: Fiscal MM-YYYY

		annotation SummarizationSetBy = Automatic

	column 'Fiscal YYYY-MM Order'
		dataType: int64
		formatString: 0
		lineageTag: 395e5810-fe07-4c05-9ac3-2cb5c723267c
		summarizeBy: none
		sourceColumn: Fiscal YYYY-MM Order

		annotation SummarizationSetBy = Automatic

	column FiscalYearsFromToday
		dataType: int64
		formatString: 0
		lineageTag: 746fdafe-0c27-4f7c-aee1-c6621eea54bb
		summarizeBy: none
		sourceColumn: FiscalYearsFromToday

		annotation SummarizationSetBy = Automatic

	column 'ISO Week'
		dataType: int64
		formatString: 0
		lineageTag: 46cb1896-2160-4871-848a-9c3282f9c0b2
		summarizeBy: none
		sourceColumn: ISO Week

		annotation SummarizationSetBy = Automatic

	column 'ISO Year'
		dataType: int64
		formatString: 0
		lineageTag: 992fde57-ce71-4e56-a326-ce01317a817f
		summarizeBy: none
		sourceColumn: ISO Year

		annotation SummarizationSetBy = Automatic

	column 'ISO Year Week'
		dataType: string
		lineageTag: b1c8694e-779a-4fd6-992f-9a57abff6bc5
		summarizeBy: none
		sourceColumn: ISO Year Week

		annotation SummarizationSetBy = Automatic

	column 'ISO Year Week Order'
		dataType: int64
		formatString: 0
		lineageTag: df5a219a-9f1b-49a5-bf5a-0c8b462a20b4
		summarizeBy: none
		sourceColumn: ISO Year Week Order

		annotation SummarizationSetBy = Automatic

	column L365D?
		dataType: int64
		formatString: 0
		lineageTag: 359959a4-f1f9-42e7-a8e4-7ce19f8fe7d7
		summarizeBy: none
		sourceColumn: L365D?

		annotation SummarizationSetBy = Automatic

	column ISOYearsFromActualISOYear
		dataType: int64
		formatString: 0
		lineageTag: 5876bab0-1a95-45df-828b-4b7d62353c47
		summarizeBy: none
		sourceColumn: ISOYearsFromActualISOYear

		annotation SummarizationSetBy = Automatic

	column ISOWeeksFromCurrentISOWeek
		dataType: int64
		formatString: 0
		lineageTag: 4a8e917f-c71c-477f-9028-7a2f4fd01c95
		summarizeBy: none
		sourceColumn: ISOWeeksFromCurrentISOWeek

		annotation SummarizationSetBy = Automatic

	column UntilCurrentFiscalMonthPeriod
		dataType: int64
		formatString: 0
		lineageTag: 64baf090-4650-4a0c-aa4a-91882f1f42e5
		summarizeBy: none
		sourceColumn: UntilCurrentFiscalMonthPeriod

		annotation SummarizationSetBy = Automatic

	partition DimDate-eb51391a-f44b-44e9-99a6-aa18d6ec8a94 = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"ac59d99b-54bb-4aaf-ba58-b30d5ae333d3" = Workspaces{[workspaceId="ac59d99b-54bb-4aaf-ba58-b30d5ae333d3"]}[Data],
				    #"1bf59c31-9295-4c06-a499-bbc9956b7b4e" = #"ac59d99b-54bb-4aaf-ba58-b30d5ae333d3"{[dataflowId="1bf59c31-9295-4c06-a499-bbc9956b7b4e"]}[Data],
				    DimDate_ = #"1bf59c31-9295-4c06-a499-bbc9956b7b4e"{[entity="DimDate",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(DimDate_, each [Date] >= StartDate and [Date] < Today)
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

