table RelationCapacityGroupsDatasets
	lineageTag: 036f0a71-2172-469d-a49f-273f7393d6c1

	column CapacityId
		dataType: string
		lineageTag: c1837d49-24b0-4fca-bef9-77376f35e198
		summarizeBy: none
		sourceColumn: CapacityId

		annotation SummarizationSetBy = Automatic

	column CapacityName
		dataType: string
		lineageTag: 7cdafd65-c816-4488-854f-e73370ec2fd1
		summarizeBy: none
		sourceColumn: CapacityName

		annotation SummarizationSetBy = Automatic

	column GroupId
		dataType: string
		lineageTag: f69fa895-205b-4dea-8a8d-a888f8cae749
		summarizeBy: none
		sourceColumn: GroupId

		annotation SummarizationSetBy = Automatic

	column GroupName
		dataType: string
		lineageTag: ce93913b-d640-4104-878f-233703b6e6e7
		summarizeBy: none
		sourceColumn: GroupName

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: 072e0413-149e-4b2e-b303-004eb35b4dd5
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: 67fc239b-522a-4592-955b-1d4d4baed65f
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column Owner
		dataType: string
		lineageTag: 5260985d-8b04-4630-9333-46162d3dadf0
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column 'Workspace Url'
		dataType: string
		lineageTag: 67f2d903-187c-4bf0-b564-3e4e023e7117
		summarizeBy: none
		sourceColumn: Workspace Url

		annotation SummarizationSetBy = Automatic

	partition RelationCapacityGroupsDatasets-d6c84033-2ec0-4116-a798-443d61a0353e = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"6c3250c1-cd1a-4bb8-acb7-0518bc2c8151" = Workspaces{[workspaceId="6c3250c1-cd1a-4bb8-acb7-0518bc2c8151"]}[Data],
				    #"e9e9ea33-99d3-4f97-9fd9-7c0e43f4c844" = #"6c3250c1-cd1a-4bb8-acb7-0518bc2c8151"{[dataflowId="e9e9ea33-99d3-4f97-9fd9-7c0e43f4c844"]}[Data],
				    RelationCapacityGroupsDatasets_ = #"e9e9ea33-99d3-4f97-9fd9-7c0e43f4c844"{[entity="RelationCapacityGroupsDatasets",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(RelationCapacityGroupsDatasets_, each [DatasetId] <> null and [DatasetId] <> ""),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"GroupId"}, #"WS-Owners", {"WorkspaceId"}, "WS-Owners", JoinKind.LeftOuter),
				    #"Expanded WS-Owners" = Table.ExpandTableColumn(#"Merged Queries", "WS-Owners", {"Owner"}, {"Owner"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Expanded WS-Owners", "Merged", each Text.Combine({"https://app.powerbi.com/groups/", [GroupId], "/"}), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "Workspace Url"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

