table WS-Owners
	lineageTag: ae514777-818c-44a3-9a0f-c610d6cfe89e

	column Owner
		dataType: string
		lineageTag: 3b291ceb-b2dc-4686-bf87-a0f13e1c97d5
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column Sub-Owner
		dataType: string
		lineageTag: 06598646-af17-47af-a2e2-d1b184823e26
		summarizeBy: none
		sourceColumn: Sub-Owner

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: 79a0164e-abfd-410c-8c9d-d1fef15e01b8
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column WorkspaceId
		dataType: string
		lineageTag: ca120c55-9f4a-456a-bc17-d33aebeddcf0
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column AppName
		dataType: string
		lineageTag: 8b6e7472-8124-4110-b03d-cc00d063a556
		summarizeBy: none
		sourceColumn: AppName

		annotation SummarizationSetBy = Automatic

	column AppId
		dataType: string
		lineageTag: d23986f3-d445-4f0a-8b44-a43e762d5dd7
		summarizeBy: none
		sourceColumn: AppId

		annotation SummarizationSetBy = Automatic

	column PII?
		dataType: int64
		formatString: 0
		lineageTag: 3accec08-269e-4b83-9952-cb9e6c1cd00c
		summarizeBy: none
		sourceColumn: PII?

		annotation SummarizationSetBy = Automatic

	column Test?
		dataType: int64
		formatString: 0
		lineageTag: 956829f9-f226-4b3d-b85d-2c5982f03a37
		summarizeBy: none
		sourceColumn: Test?

		annotation SummarizationSetBy = Automatic

	column WorkspaceDeleted?
		dataType: int64
		formatString: 0
		lineageTag: 1c329c62-7977-4c36-80eb-ee7f0c63b857
		summarizeBy: none
		sourceColumn: WorkspaceDeleted?

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 5f8a09d4-4149-44d9-9bb8-5d15bec070d8
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	partition WS-Owners-b3bff3b5-5646-4545-9030-5f4d5a752d7e = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/Documentation/List%20of%20Workspaces.xlsx"), null, true),
				    #"WS-Owners_Sheet" = Source{[Item="WS-Owners",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"WS-Owners_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Owner", type text}, {"Sub-Owner", type any}, {"WorkspaceName", type text}, {"WorkspaceId", type text}, {"AppName", type text}, {"AppId", type text}, {"PII?", Int64.Type}, {"Test?", Int64.Type}, {"WorkspaceDeleted?", Int64.Type}, {"Comments", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([WorkspaceName] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

