table 'DashboardDeleted(MakeRunning - 0)'
	lineageTag: b1a37948-e69c-4947-a204-78d8233f5c1e

	column DashboardID
		dataType: string
		lineageTag: f6f411be-0eb7-4353-9964-9ac9b5f17a31
		summarizeBy: none
		sourceColumn: DashboardID

		annotation SummarizationSetBy = Automatic

	column DashboardName
		dataType: string
		lineageTag: dfe7e18e-93c5-47dc-87b7-3b8efe68b1cb
		summarizeBy: none
		sourceColumn: DashboardName

		annotation SummarizationSetBy = Automatic

	column Running
		dataType: int64
		formatString: 0
		lineageTag: 63115df4-64e0-45bf-8e46-8e816fc5062b
		summarizeBy: sum
		sourceColumn: Running

		annotation SummarizationSetBy = Automatic

	partition 'DashboardDeleted(MakeRunning - 0)-30baf39e-5c38-4a94-8ce8-3b7ea9d2967a' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/PBI%20Reports/Power%20BI%20-%20Info/Subscriptions/PowerBIDashboardEmailSubscriptions.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DashboardID", type text}, {"DashboardName", type text}, {"Running", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"DashboardID"}, CreatedSubscriptionsByDashboard_API, {"artifactId"}, "CreatedSubscriptionsByDashboard_API", JoinKind.LeftAnti),
				    #"Filtered Rows" = Table.SelectRows(#"Merged Queries", each ([Running] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

