table ReportDetails(Excel)
	lineageTag: e54be262-9f6b-43c5-94f1-d91bbbebaa21

	column ReportId
		dataType: string
		lineageTag: f5e7f5fd-6cf8-47df-bf93-8235d58981fd
		summarizeBy: none
		sourceColumn: ReportId

		annotation SummarizationSetBy = Automatic

	column ReportName
		dataType: string
		lineageTag: 8e8f5c98-7be5-4c79-92bb-d13b736c0651
		summarizeBy: none
		sourceColumn: ReportName

		annotation SummarizationSetBy = Automatic

	column Running
		dataType: int64
		formatString: 0
		lineageTag: fd7cf3d3-01d5-446b-a682-bcc4cee6393f
		summarizeBy: sum
		sourceColumn: Running

		annotation SummarizationSetBy = Automatic

	partition ReportDetails(Excel)-0a8c9dc9-add4-49a3-a21a-f5de188b56ce = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/PBI%20Reports/Power%20BI%20-%20Info/Subscriptions/PowerBIReportEmailSubscriptions.xlsx"), null, true),
				    data_Sheet = Source{[Item="data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReportId", type text}, {"ReportName", type text}, {"Running", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

