table Gateways
	lineageTag: 052cefd3-6103-4e95-bf7c-327021507bdc

	column GatewayID
		dataType: string
		lineageTag: ad405fb9-9087-497e-ac10-65db4105c0e6
		summarizeBy: none
		sourceColumn: GatewayID

		annotation SummarizationSetBy = Automatic

	column GatewayName
		dataType: string
		lineageTag: bc09e312-f6bc-47d8-9d46-3a166ea7bd56
		summarizeBy: none
		sourceColumn: GatewayName

		annotation SummarizationSetBy = Automatic

	column 'VM ID'
		dataType: string
		lineageTag: 468bc490-0f59-4d3d-90d8-d4a100ba1de6
		summarizeBy: none
		sourceColumn: VM ID

		annotation SummarizationSetBy = Automatic

	column 'VM Name'
		dataType: string
		lineageTag: 26cd587d-cf51-4cc8-8e62-ec59a6a22737
		summarizeBy: none
		sourceColumn: VM Name

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: 37ba6e1d-45fa-4575-b195-9d6839f1b9d0
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	partition Gateways = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/PBI%20Reports/Power%20BI%20-%20Info/DataSources/Gateways%20and%20VM's.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sheet1_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"GatewayID", type text}, {"GatewayName", type text}, {"VM ID", type text}, {"VM Name", type text}, {"Notes", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

