table KeyMeasures
	lineageTag: e4e6d924-527a-40a2-9280-d742f59fdafe

	measure #OperationsYesterday = CALCULATE(count(pbi_activityevents[itemname]),dim_date[Date] = TODAY()-1,pbi_activityevents[userid] <> "Francisco.Gonzalez@EntainGroup.com")
		formatString: 0
		lineageTag: 40c30913-7577-403d-ba00-934dc647126e

	measure #Operations = count(pbi_activityevents[itemname])
		formatString: 0
		lineageTag: 7e0b40e4-4abb-4145-8f4e-3a8a4d28c250

	partition KeyMeasures-84292e6f-7b1c-465f-bd8b-209398f10561 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

