table pbi_activityevents
	lineageTag: 29117ce5-a8a4-4f80-97e4-6e53a1f0a31e

	column activity
		dataType: string
		lineageTag: 32ac8fd3-b7e5-49ae-8a45-c0d449bad33d
		summarizeBy: none
		sourceColumn: activity

		annotation SummarizationSetBy = Automatic

	column activityid
		dataType: string
		lineageTag: 6a205266-8faf-46a5-b47f-584a61296e0e
		summarizeBy: none
		sourceColumn: activityid

		annotation SummarizationSetBy = Automatic

	column capacityname
		dataType: string
		lineageTag: 2ef65c90-2ff9-4e0a-bf4e-8bf259ad9f28
		summarizeBy: none
		sourceColumn: capacityname

		annotation SummarizationSetBy = Automatic

	column clientip
		dataType: string
		lineageTag: 44fa8679-b193-4851-93a1-b59282733e02
		summarizeBy: none
		sourceColumn: clientip

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: f5ab8e3a-da90-42e8-9679-8a29b58c7e27
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column issuccess
		dataType: string
		lineageTag: 7ca2bfd1-706f-46ef-8bc7-a10e6f5fb54a
		summarizeBy: none
		sourceColumn: issuccess

		annotation SummarizationSetBy = Automatic

	column itemname
		dataType: string
		lineageTag: 266d4693-9cb8-4e8d-beb9-182f568a15f6
		summarizeBy: none
		sourceColumn: itemname

		annotation SummarizationSetBy = Automatic

	column objectid
		dataType: string
		lineageTag: f9cf3f73-142d-42d7-b9ed-b2214051904a
		summarizeBy: none
		sourceColumn: objectid

		annotation SummarizationSetBy = Automatic

	column operation
		dataType: string
		lineageTag: 8c0ba893-f2e8-417f-8b8c-fa18b654776e
		summarizeBy: none
		sourceColumn: operation

		annotation SummarizationSetBy = Automatic

	column organizationid
		dataType: string
		lineageTag: cf613252-8692-47e2-b0fb-9e4624ca38bd
		summarizeBy: none
		sourceColumn: organizationid

		annotation SummarizationSetBy = Automatic

	column recordtype
		dataType: string
		lineageTag: dbb19e51-1450-4e8d-9368-79f0ae630fba
		summarizeBy: none
		sourceColumn: recordtype

		annotation SummarizationSetBy = Automatic

	column requestid
		dataType: string
		lineageTag: 5cd52dd3-44e6-41a5-89e2-be88338f9a7e
		summarizeBy: none
		sourceColumn: requestid

		annotation SummarizationSetBy = Automatic

	column useragent
		dataType: string
		lineageTag: 9e7ea503-986a-449c-bf50-9a95db928a61
		summarizeBy: none
		sourceColumn: useragent

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 7a3f29ef-beff-4474-9c5e-4cfe955cc70b
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column userkey
		dataType: string
		lineageTag: 59f38a96-34a2-4a3a-9809-2646d25a42a0
		summarizeBy: none
		sourceColumn: userkey

		annotation SummarizationSetBy = Automatic

	column usertype
		dataType: string
		lineageTag: baa4f596-09f3-4ac3-aa5c-e5e053048011
		summarizeBy: none
		sourceColumn: usertype

		annotation SummarizationSetBy = Automatic

	column workload
		dataType: string
		lineageTag: fc3d6c50-91d1-4797-a92b-cf9afd1092ac
		summarizeBy: none
		sourceColumn: workload

		annotation SummarizationSetBy = Automatic

	column loaddatenumber
		dataType: int64
		formatString: 0
		lineageTag: 0b4b80ec-3134-41a1-89dc-efb87e0d85b6
		summarizeBy: sum
		sourceColumn: loaddatenumber

		annotation SummarizationSetBy = Automatic

	column CreationDate
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: e1b3fc49-5e64-4a35-8ebc-bd14791efc88
		summarizeBy: none
		sourceColumn: CreationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column CreationTime
		dataType: dateTime
		formatString: Long Time
		lineageTag: bd8629cf-76ad-4d96-a471-c32c44a0c4f2
		summarizeBy: none
		sourceColumn: CreationTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition pbi_activityevents-6086aa92-a9dc-4843-9dde-e26fbc904450 = m
		mode: import
		source = ```
				let
				    Source=Value.NativeQuery(Snowflake.Databases(ServerName,WarehouseName,[Role=RoleName]){[Name=DatabaseName]}[Data],  
				    "select * from EDLRETAILVIEWSBI.pbi_activityevents where activity = 'UpdateCapacityResourceGovernanceSettings' or activity = 'UpdateCapacityCustomSettings' or activity = 'UpdatedAdminFeatureSwitch' or activity = 'Updated workspace Analysis Services settings'", null, [EnableFolding=true]),
				    LowercaseColumnNames = Table.TransformColumnNames(Source, Text.Lower),
				    #"Split Column by Delimiter" = Table.SplitColumn(LowercaseColumnNames, "creationtime", Splitter.SplitTextByDelimiter("T", QuoteStyle.None), {"CreationDate", "CreationTime"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"CreationDate", type date}, {"CreationTime", type time}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"activity", "activityid", "capacityname", "clientip", "CreationDate", "CreationTime", "id", "issuccess", "itemname", "objectid", "operation", "organizationid", "recordtype", "requestid", "useragent", "userid", "userkey", "usertype", "workload", "loaddatenumber"})
				in
				    #"Removed Other Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

