table ConnectorDetails
	lineageTag: 42c14531-5bd2-46e1-a68b-6cfb4a0e177b

	column GatewayId
		dataType: string
		lineageTag: cd836148-dfd8-4f07-8abc-4a569d6afe8b
		summarizeBy: none
		sourceColumn: GatewayId

		annotation SummarizationSetBy = Automatic

	column ClusterGatewayId
		dataType: string
		lineageTag: 5ad31906-c34e-412a-ab20-d5bc2bf9c34e
		summarizeBy: none
		sourceColumn: ClusterGatewayId

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: b299fc5d-1b4a-47ff-bf6f-6e677f6c3838
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 5f0f7c4e-f14e-45cf-abb2-371877d25ad2
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column gatewayAnnotation
		dataType: string
		lineageTag: b6e77eb2-23e3-496c-85c9-6d115c0c97ff
		summarizeBy: none
		sourceColumn: gatewayAnnotation

		annotation SummarizationSetBy = Automatic

	column DataSourceId
		dataType: string
		lineageTag: 9fbf2fd1-b97e-45e8-8dd2-08748cc944cd
		summarizeBy: none
		sourceColumn: DataSourceId

		annotation SummarizationSetBy = Automatic

	column datasourceType
		dataType: string
		lineageTag: fd06689b-d7ff-45f2-bba1-ee5c03188ffa
		summarizeBy: none
		sourceColumn: datasourceType

		annotation SummarizationSetBy = Automatic

	column connectionDetails
		dataType: string
		lineageTag: 47cdef2a-29c9-4fc0-b80b-85888038fa5b
		summarizeBy: none
		sourceColumn: connectionDetails

		annotation SummarizationSetBy = Automatic

	column credentialType
		dataType: string
		lineageTag: 0c1a3d5f-38c1-4761-bcfe-f651ef47c827
		summarizeBy: none
		sourceColumn: credentialType

		annotation SummarizationSetBy = Automatic

	column privacyLevel
		dataType: string
		lineageTag: d248fe17-5fe1-4149-a212-d401cc5b0591
		summarizeBy: none
		sourceColumn: privacyLevel

		annotation SummarizationSetBy = Automatic

	column useEndUserOAuth2Credentials
		dataType: string
		lineageTag: 4b783b53-e50b-41f7-9921-6053b6a2cd4f
		summarizeBy: none
		sourceColumn: useEndUserOAuth2Credentials

		annotation SummarizationSetBy = Automatic

	column datasourceName
		dataType: string
		lineageTag: 5e781aae-bbc6-4728-bb70-034f2b024b4d
		summarizeBy: none
		sourceColumn: datasourceName

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: 80f40b26-cf7a-4b1a-9e81-63f0c63f4db7
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column DatasetName
		dataType: string
		lineageTag: bd0f9703-c506-4158-8fef-5fafca7796c7
		summarizeBy: none
		sourceColumn: DatasetName

		annotation SummarizationSetBy = Automatic

	column Views
		dataType: double
		formatString: #,0
		lineageTag: f0acd33e-5f2b-4bff-a7fd-7417aeef93e8
		summarizeBy: sum
		sourceColumn: Views

		annotation SummarizationSetBy = Automatic

	column Views_90days
		dataType: double
		formatString: #,0
		lineageTag: 9162c709-9bec-47e0-83a7-b6e9f677a021
		summarizeBy: sum
		sourceColumn: Views_90days

		annotation SummarizationSetBy = Automatic

	column Views_60days
		dataType: double
		formatString: #,0
		lineageTag: 9a7a8c28-194b-4af3-9ae9-e04f7865b825
		summarizeBy: sum
		sourceColumn: Views_60days

		annotation SummarizationSetBy = Automatic

	column Views_30days
		dataType: double
		formatString: #,0
		lineageTag: cebf6486-06bc-4923-a425-5fc9d0a0a3fa
		summarizeBy: sum
		sourceColumn: Views_30days

		annotation SummarizationSetBy = Automatic

	column 'VM ID'
		dataType: string
		lineageTag: ec79b9dc-adf2-45f6-831d-3a83b51816e8
		summarizeBy: none
		sourceColumn: VM ID

		annotation SummarizationSetBy = Automatic

	column 'VM Name'
		dataType: string
		lineageTag: 9fbcb2f0-ba94-404b-af76-772663fc6155
		summarizeBy: none
		sourceColumn: VM Name

		annotation SummarizationSetBy = Automatic

	column Notes
		dataType: string
		lineageTag: 32e48147-82fb-44d4-a7de-251383e92df9
		summarizeBy: none
		sourceColumn: Notes

		annotation SummarizationSetBy = Automatic

	partition ConnectorDetails = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"6c3250c1-cd1a-4bb8-acb7-0518bc2c8151" = Workspaces{[workspaceId="6c3250c1-cd1a-4bb8-acb7-0518bc2c8151"]}[Data],
				    #"c55614e1-8234-4ef9-827e-cdf18b4a0cb8" = #"6c3250c1-cd1a-4bb8-acb7-0518bc2c8151"{[dataflowId="c55614e1-8234-4ef9-827e-cdf18b4a0cb8"]}[Data],
				    GatewayConnectors_ = #"c55614e1-8234-4ef9-827e-cdf18b4a0cb8"{[entity="GatewayConnectors",version=""]}[Data],
				    #"Merged Queries" = Table.NestedJoin(GatewayConnectors_, {"DataSourceId"}, DataSourcesByDatasetId, {"datasourceId"}, "DataSourcesByDatasetId", JoinKind.LeftOuter),
				    #"Expanded DataSourcesByDatasetId" = Table.ExpandTableColumn(#"Merged Queries", "DataSourcesByDatasetId", {"DatasetId", "DatasetName", "Views", "Views_90days", "Views_60days", "Views_30days"}, {"DatasetId", "DatasetName", "Views", "Views_90days", "Views_60days", "Views_30days"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Expanded DataSourcesByDatasetId", {"GatewayId"}, Gateways, {"GatewayID"}, "Gateways", JoinKind.LeftOuter),
				    #"Expanded Gateways" = Table.ExpandTableColumn(#"Merged Queries1", "Gateways", {"VM ID", "VM Name", "Notes"}, {"VM ID", "VM Name", "Notes"})
				in
				    #"Expanded Gateways"

	annotation PBI_ResultType = Table

