table 'Key Measures'
	lineageTag: bc4202d3-d6f8-46b5-a9dc-035883d7ead8

	measure Reader = ```
			
			VAR MaxValue =
			    ADDCOLUMNS (
			        SUMMARIZE (
			            AppsUsers,
			            AppsUsers[AppName],
			            AppsUsers[displayName],
			            AppsUsers[Having readergroups/not]
			        ),
			        "_val",
			         
			                MAX (AppsUsers[Having readergroups/not])
			            )
			    RETURN
			    IF ( SUMX ( MaxValue, [_val] ) = 0, "No Reader Group","Reader Group" )
			```
		lineageTag: a7a3cf8b-aa22-4f96-ae45-ae3844a8b9d7

	partition 'Key Measures-74307b75-9134-47cb-a0f9-4081b96b4f5a' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

