table PageSecurity
	lineageTag: 44e605ca-db35-4128-b667-4da3ce5a420a

	measure 'User used' = USERPRINCIPALNAME()
		lineageTag: e18660d7-dd20-43b0-85d6-a571574cb0a5

	measure Selectedpage = SELECTEDVALUE(PageSecurity[Page])
		lineageTag: 11a8ab1a-142a-45c9-b826-ff3153206622

	column Page
		dataType: string
		lineageTag: 401bbe83-a784-4b7f-87e1-0a5f4f5a465d
		summarizeBy: none
		sourceColumn: Page

		annotation SummarizationSetBy = Automatic

	column User
		dataType: string
		lineageTag: 21e8ae40-9616-43e7-9ae1-1e2cd14ff776
		summarizeBy: none
		sourceColumn: User

		annotation SummarizationSetBy = Automatic

	partition PageSecurity-16d5a82c-f98b-496b-b3f7-adf74432b791 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCkpNTEktUnAvyi8tKFbSUXIrSsxLzixOztdzz8+rSsxJrXJwzStJzMwDq9BLzs9Vio0FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Page = _t, User = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Page", type text}, {"User", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

