table WS-Owners
	lineageTag: 019b5550-03df-4344-896b-04e329fc00fd

	column Owner
		dataType: string
		lineageTag: 597d5b00-feea-4ac1-8745-38d80488b5a5
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column Sub-Owner
		dataType: string
		lineageTag: 997ead40-88aa-4007-b9eb-46e4c2206eed
		summarizeBy: none
		sourceColumn: Sub-Owner

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: 257f73b0-62ac-41c3-99cc-8568674f3ab5
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column WorkspaceId
		dataType: string
		lineageTag: 363ee958-dc8e-4aa3-a5b6-65be6ac6c98a
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column AppName
		dataType: string
		lineageTag: 8f72c92b-29bb-46c0-b76f-4595aed2f6cf
		summarizeBy: none
		sourceColumn: AppName

		annotation SummarizationSetBy = Automatic

	column AppId
		dataType: string
		lineageTag: be24e783-2262-453b-8da3-29fc1443b3d0
		summarizeBy: none
		sourceColumn: AppId

		annotation SummarizationSetBy = Automatic

	column PII?
		dataType: int64
		formatString: 0
		lineageTag: c62e07d3-c6e4-4e06-ab0b-b2617591c332
		summarizeBy: sum
		sourceColumn: PII?

		annotation SummarizationSetBy = Automatic

	column Test?
		dataType: int64
		formatString: 0
		lineageTag: a951b797-d3d4-4b67-a909-89d2d151cd58
		summarizeBy: sum
		sourceColumn: Test?

		annotation SummarizationSetBy = Automatic

	column WorkspaceDeleted?
		dataType: int64
		formatString: 0
		lineageTag: f5e0d004-26d6-4243-b68e-82a1a411f7de
		summarizeBy: sum
		sourceColumn: WorkspaceDeleted?

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 34056de9-4052-43c7-9d0a-ed3a1f558a43
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	partition WS-Owners-27d70c54-00d4-4a50-9c74-a6be96459ce2 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/Documentation/List%20of%20Workspaces.xlsx"), null, true),
				    #"WS-Owners_Sheet" = Source{[Item="WS-Owners",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"WS-Owners_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Owner", type text}, {"Sub-Owner", type any}, {"WorkspaceName", type text}, {"WorkspaceId", type text}, {"AppName", type text}, {"AppId", type text}, {"PII?", Int64.Type}, {"Test?", Int64.Type}, {"WorkspaceDeleted?", Int64.Type}, {"Comments", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [AppName] <> null)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

