table 'Key Measures'
	lineageTag: cf57c687-2770-476c-890c-81f27d79bbe1

	measure '# Rows' = SUM(pbi_activityevents[count])
		formatString: #,0
		lineageTag: c835e4b5-073e-4e65-988b-720a6e827c57

	measure '# Views' = ```
			
			
			    [# Rows]
			```
		formatString: #,0
		lineageTag: d8fb0f07-f59c-4dd3-adb8-31e36ead3a07

		changedProperty = FormatString

	measure 'MA L7D AVG Views' =
			
			CALCULATE (
			    [AVG Views per Day],
			    DATESINPERIOD( DimDate[Date], LASTDATE ( DimDate[Date] ), -7, DAY )
			)
		formatString: #,0
		lineageTag: 754bd0a1-f075-4a1d-85a7-e7f18d6dbd73

		changedProperty = FormatString

	measure 'AVG Views per Day' = AVERAGEX(VALUES(DimDate[Date]), [# Views])
		formatString: #,0.0
		lineageTag: 3b470dad-61be-45e2-8396-5fa56a6589b8

		changedProperty = FormatString

	measure '# Active Users' = SUMX(DISTINCT(pbi_activityevents[userid]),1)
		formatString: #,0
		lineageTag: 2dd7233b-6d55-4227-8898-43c7f5785ddf

		changedProperty = FormatString

	measure 'AVG Views per User' = AVERAGEX(VALUES(pbi_activityevents[userid]), [# Views])
		formatString: #,0.0
		lineageTag: 04aeb2c4-5b8a-4cad-adf4-60074ccc1054

		changedProperty = FormatString

	measure 'AVG Views per User & Day' = DIVIDE([AVG Views per User], COUNTROWS(VALUES(pbi_activityevents[CreationDate])))
		formatString: #,0.0
		lineageTag: 90c96963-b8ca-460e-bb02-d9e9dfce409c

		changedProperty = FormatString

	measure '# Days' = COUNTROWS(VALUES(pbi_activityevents[CreationDate]))
		formatString: #,0
		lineageTag: 0b65c4e2-5eb3-472d-bb9b-1c3be76a7517

	measure WAU =
			
			CALCULATE (
			    [# Active Users],
			    DATESINPERIOD( DimDate[Date], LASTDATE ( DimDate[Date] ), -7, DAY )
			)
		formatString: #,0
		lineageTag: 76a70e39-f1ed-4c40-a4eb-68cfb903ed69

		changedProperty = FormatString

	measure 'AVG Active Users per Day' = AVERAGEX(VALUES(DimDate[Date]), [# Active Users])
		formatString: #,0.0
		lineageTag: fe03d224-2f1e-4526-9018-e5d2166857cc

		changedProperty = FormatString

	measure MAU =
			
			CALCULATE (
			    [# Active Users],
			    DATESINPERIOD( DimDate[Date], LASTDATE ( DimDate[Date] ), -1, MONTH )
			)
		formatString: #,0
		lineageTag: 8b54c20d-b03b-4d57-bd28-97148492f8f3

		changedProperty = FormatString

	measure DAU =
			
			CALCULATE (
			    [# Active Users],
			    DATESINPERIOD( DimDate[Date], LASTDATE ( DimDate[Date] ), -1, DAY )
			)
		formatString: #,0
		lineageTag: 3a2a8e61-0ed1-475c-aa92-a45c6b3c06c7

		changedProperty = FormatString

	measure '% DAU/MAU' = DIVIDE([DAU],[MAU])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 521ed45b-e532-4e60-b707-a0153710eb7d

		changedProperty = FormatString

	measure '% DAU/WAU' = DIVIDE([DAU],[WAU])
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 756b3049-4a28-4b1b-9e38-7d1f0afeb367

		changedProperty = FormatString

	measure 'L30D Views' = CALCULATE([# Views],DATESINPERIOD(DimDate[Date],LASTDATE(DimDate[Date]),-30,DAY))
		formatString: #,0
		lineageTag: 5756164d-f0e0-4e83-9718-be4a3b2b0b89

	measure 'L60D Views' = CALCULATE([# Views],DATESINPERIOD(DimDate[Date],LASTDATE(DimDate[Date]),-60,DAY))
		formatString: #,0
		lineageTag: 042e4ea9-30a5-400d-8ce5-3f9399261eb3

	measure 'L90D Views' = CALCULATE([# Views],DATESINPERIOD(DimDate[Date],LASTDATE(DimDate[Date]),-90,DAY))
		formatString: #,0
		lineageTag: 2af01017-1365-4114-a6b0-0b61f65f9342

	measure 'L30D Unique Users' = CALCULATE([# Active Users],DATESINPERIOD(DimDate[Date],LASTDATE(DimDate[Date]),-30,DAY))
		formatString: #,0
		lineageTag: 8aed0b45-bc9b-4b39-95e8-eac5ff00ef0a

	measure 'L60D Unique Users' = CALCULATE([# Active Users],DATESINPERIOD(DimDate[Date],LASTDATE(DimDate[Date]),-60,DAY))
		formatString: #,0
		lineageTag: 436109d6-48bb-45d0-a08d-644a10711d1d

	measure 'L90D Unique Users' = CALCULATE([# Active Users],DATESINPERIOD(DimDate[Date],LASTDATE(DimDate[Date]),-90,DAY))
		formatString: #,0
		lineageTag: c3352207-2d66-4ec5-8eef-d76b1ad9ecab

	measure 'Rank for Total Views' = IF(([# Views])<>BLANK(),RANKX(ALL(RelationCapacityGroupsReports[ReportName]),[# Views]))
		formatString: #,0
		lineageTag: 3751e660-6116-4007-ab26-5e211e9761c0

	measure 'CT for Total Views' = CALCULATE([# Views],TOPN([Rank for Total Views],ALLSELECTED(RelationCapacityGroupsReports),[# Views]))
		formatString: #,0
		lineageTag: ca89fed7-42b6-4891-83ff-189fcb686144

	measure '% Total Views' = DIVIDE([CT for Total Views],CALCULATE([# Views],ALLSELECTED(RelationCapacityGroupsReports)))
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 3873346b-ec98-49fd-a896-e219cd459c4b

	measure 'L60D Views AnalyzeByExternalApplication' = CALCULATE([# Views],DATESINPERIOD(DimDate[Date],LASTDATE(DimDate[Date]),-60,DAY),FILTER(pbi_activityevents,pbi_activityevents[activity] IN {"AnalyzedByExternalApplication", "AnalyzeInExcel","ConnectFromExternalApplication"}))
		formatString: 0
		lineageTag: ea8c78a9-9758-430c-9b17-9fe4d485ce69

	partition 'Key Measures-8d5fc69d-e01e-4096-9222-d4a7aa001e7f' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

