table RelationCapacityGroupsReports
	lineageTag: 0dca84c5-7855-44b6-8ab8-49ae188a1b15

	column isReadOnly
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7b6461c9-ec96-48d0-a3f2-33d5044cf2f0
		summarizeBy: none
		sourceColumn: isReadOnly

		annotation SummarizationSetBy = Automatic

	column isOnDedicatedCapacity
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3ed4a465-f665-4095-9de8-7e5751fe3653
		summarizeBy: none
		sourceColumn: isOnDedicatedCapacity

		annotation SummarizationSetBy = Automatic

	column capacityMigrationStatus
		dataType: string
		lineageTag: e5c3b9a7-8ad5-4d33-8d98-61a821117968
		summarizeBy: none
		sourceColumn: capacityMigrationStatus

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 0b28cc4b-3143-4ac0-af77-0769ee95bda1
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 3e3dd8d4-28db-4ccb-8984-91adaa0027d4
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column hasWorkspaceLevelSettings
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 07aaaefe-ecf8-462a-959e-7ff80a1bda22
		summarizeBy: none
		sourceColumn: hasWorkspaceLevelSettings

		annotation SummarizationSetBy = Automatic

	column CapacityId
		dataType: string
		lineageTag: db60df87-f27a-4920-89d4-ec9f90f7b9df
		summarizeBy: none
		sourceColumn: CapacityId

		annotation SummarizationSetBy = Automatic

	column CapacityNameOfReport
		dataType: string
		lineageTag: 6abc621f-536b-4fd1-965f-36b6ed1be881
		summarizeBy: none
		sourceColumn: CapacityNameOfReport

		annotation SummarizationSetBy = Automatic

	column GroupId
		dataType: string
		lineageTag: ed685d33-efb7-4771-a033-cba550049b0d
		summarizeBy: none
		sourceColumn: GroupId

		annotation SummarizationSetBy = Automatic

	column GroupName
		dataType: string
		lineageTag: 879d7d33-233d-4d0e-a501-07a80bb24bff
		summarizeBy: none
		sourceColumn: GroupName

		annotation SummarizationSetBy = Automatic

	column ReportId
		dataType: string
		lineageTag: 8688ee4b-1a45-4526-9ef7-e1c2ec9f2f04
		summarizeBy: none
		sourceColumn: ReportId

		annotation SummarizationSetBy = Automatic

	column ReportName
		dataType: string
		lineageTag: 97567d45-6ec6-4a2d-be91-99759b3f6648
		summarizeBy: none
		sourceColumn: ReportName

		annotation SummarizationSetBy = Automatic

	column reportType
		dataType: string
		lineageTag: f0bb1982-59c6-4efe-843f-ad3e5d592000
		summarizeBy: none
		sourceColumn: reportType

		annotation SummarizationSetBy = Automatic

	column DatasetId
		dataType: string
		lineageTag: 3ab08451-ba71-4be0-84f3-1aa95b6f43b8
		summarizeBy: none
		sourceColumn: DatasetId

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 58f37c9d-c601-4f82-b268-04ee91bba76c
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 81f73169-82f8-406a-bd51-770142da6182
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	column Owner
		dataType: string
		lineageTag: b73760bb-c708-4c6b-a0a1-f83b82a8c2af
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column WorkspaceUrl
		dataType: string
		lineageTag: d7571d6e-b8a6-4eba-b7a1-6d0cb012804c
		summarizeBy: none
		sourceColumn: WorkspaceUrl

		annotation SummarizationSetBy = Automatic

	partition RelationCapacityGroupsReports-8db653e1-dd48-44d9-9140-241a919ab50b = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"b1189a55-d3ea-4ceb-8dd9-994de230fca3" = Workspaces{[workspaceId="b1189a55-d3ea-4ceb-8dd9-994de230fca3"]}[Data],
				    #"72d38d67-1c11-412c-98df-4ebbd50bcc7b" = #"b1189a55-d3ea-4ceb-8dd9-994de230fca3"{[dataflowId="72d38d67-1c11-412c-98df-4ebbd50bcc7b"]}[Data],
				    RelationCapacityGroupsReports_ = #"72d38d67-1c11-412c-98df-4ebbd50bcc7b"{[entity="RelationCapacityGroupsReports",version=""]}[Data],
				    #"Filtered Rows1" = Table.SelectRows(RelationCapacityGroupsReports_, each ([state] = "Active")),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows1", {"GroupId"}, #"WS-Owners", {"WorkspaceId"}, "WS-Owners", JoinKind.LeftOuter),
				    #"Expanded WS-Owners" = Table.ExpandTableColumn(#"Merged Queries", "WS-Owners", {"Owner"}, {"Owner"}),
				    #"Inserted Merged Column" = Table.AddColumn(#"Expanded WS-Owners", "Merged", each Text.Combine({"https://app.powerbi.com/groups/", [GroupId], "/"}), type text),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Merged Column",{{"Merged", "WorkspaceUrl"}}),
				    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns", each [ReportId] <> null and [ReportId] <> ""),
				    #"Lowercased Text" = Table.TransformColumns(#"Filtered Rows",{{"ReportId", Text.Lower, type text}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Lowercased Text","[App] ","",Replacer.ReplaceText,{"ReportName"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

