table WS-Owners_RLS
	lineageTag: 277e565b-008e-40ce-8409-a14d33ee21e9

	column Owner
		dataType: string
		lineageTag: c8fcd0fa-9942-4185-88dc-084ce0601705
		summarizeBy: none
		sourceColumn: Owner

		annotation SummarizationSetBy = Automatic

	column Sub-Owner
		dataType: string
		lineageTag: b7d875d6-261f-4d0d-a2a2-5cce19d6be42
		summarizeBy: none
		sourceColumn: Sub-Owner

		annotation SummarizationSetBy = Automatic

	column WorkspaceName
		dataType: string
		lineageTag: 833578ae-fe5a-467f-9f25-9a95c4941687
		summarizeBy: none
		sourceColumn: WorkspaceName

		annotation SummarizationSetBy = Automatic

	column WorkspaceId
		dataType: string
		lineageTag: b8355a4d-1689-4f92-99fb-e14cd7620b11
		summarizeBy: none
		sourceColumn: WorkspaceId

		annotation SummarizationSetBy = Automatic

	column AppName
		dataType: string
		lineageTag: 98592c02-47a1-4aaf-b5ae-630f04447068
		summarizeBy: none
		sourceColumn: AppName

		annotation SummarizationSetBy = Automatic

	column AppId
		dataType: string
		lineageTag: 1738a587-4e86-4c1c-921c-7f8d9fb8f356
		summarizeBy: none
		sourceColumn: AppId

		annotation SummarizationSetBy = Automatic

	column PII?
		dataType: int64
		formatString: 0
		lineageTag: d124ad7d-5304-448b-b75f-555d6e3c68e7
		summarizeBy: none
		sourceColumn: PII?

		annotation SummarizationSetBy = Automatic

	column Test?
		dataType: int64
		formatString: 0
		lineageTag: dcd74332-9031-4a57-8bcb-841d07f65f11
		summarizeBy: none
		sourceColumn: Test?

		annotation SummarizationSetBy = Automatic

	column WorkspaceDeleted?
		dataType: int64
		formatString: 0
		lineageTag: 6f3a29de-cb1e-4e5e-a368-ee840821f838
		summarizeBy: none
		sourceColumn: WorkspaceDeleted?

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 5765614d-b50f-44bd-a426-fe256580b9f7
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	partition WS-Owners_RLS-7ab1353b-1c43-4ffc-82df-624e442fd521 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/Documentation/List%20of%20Workspaces.xlsx"), null, true),
				    #"WS-Owners_Sheet" = Source{[Item="WS-Owners",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"WS-Owners_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Owner", type text}, {"Sub-Owner", type any}, {"WorkspaceName", type text}, {"WorkspaceId", type text}, {"AppName", type text}, {"AppId", type text}, {"PII?", Int64.Type}, {"Test?", Int64.Type}, {"WorkspaceDeleted?", Int64.Type}, {"Comments", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([WorkspaceName] <> null))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

