table Artifacts
	lineageTag: 5725ee8b-4598-4865-ab7d-8117ea3012c5

	column isReadOnly
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 26a9791a-925b-48a1-94dc-aa1a019ac3d4
		summarizeBy: none
		sourceColumn: isReadOnly

		annotation SummarizationSetBy = Automatic

	column isOnDedicatedCapacity
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d46b314c-2358-4a61-8309-a060edcaf48f
		summarizeBy: none
		sourceColumn: isOnDedicatedCapacity

		annotation SummarizationSetBy = Automatic

	column capacityMigrationStatus
		dataType: string
		lineageTag: 1572c9e9-a51f-4795-b914-79904813d395
		summarizeBy: none
		sourceColumn: capacityMigrationStatus

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 702f4e71-cd61-406c-8192-bfa11ee492e5
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 855eefe4-34cb-42f3-8f1f-42e480fabae4
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column hasWorkspaceLevelSettings
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: cb408b78-23dc-45a4-bb07-f5dad45a28c6
		summarizeBy: none
		sourceColumn: hasWorkspaceLevelSettings

		annotation SummarizationSetBy = Automatic

	column CapacityId
		dataType: string
		lineageTag: 4b3307b5-c86d-4bff-98c3-06733e5b72c1
		summarizeBy: none
		sourceColumn: CapacityId

		annotation SummarizationSetBy = Automatic

	column CapacityName
		dataType: string
		lineageTag: 8466af2b-beac-4354-b2b7-5d697bfdff75
		summarizeBy: none
		sourceColumn: CapacityName

		annotation SummarizationSetBy = Automatic

	column GroupId
		dataType: string
		lineageTag: 33f3fa6b-1542-4b99-8f5d-859134ff0a83
		summarizeBy: none
		sourceColumn: GroupId

		annotation SummarizationSetBy = Automatic

	column GroupName
		dataType: string
		lineageTag: 8168e92a-fa26-4fec-9507-0000711ba3bd
		summarizeBy: none
		sourceColumn: GroupName

		annotation SummarizationSetBy = Automatic

	column ArtifactId
		dataType: string
		lineageTag: b42b450f-e466-4b5b-94d6-1ebbbaa7a29a
		summarizeBy: none
		sourceColumn: ArtifactId

		annotation SummarizationSetBy = Automatic

	column ArtifactName
		dataType: string
		lineageTag: 02d7569c-f52e-4763-94c3-a0e4697b3b07
		summarizeBy: none
		sourceColumn: ArtifactName

		annotation SummarizationSetBy = Automatic

	column description
		dataType: string
		lineageTag: 83d5986e-baaf-41d1-96de-9b00a57d7a58
		summarizeBy: none
		sourceColumn: description

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: 0c27ac9e-2547-430a-9beb-41153dcb8c5d
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = Automatic

	partition Artifacts-0679ce28-ba25-49c2-99f2-00ea309af9c7 = m
		mode: import
		source =
				let
				    Source = PowerPlatform.Dataflows(null),
				    Workspaces = Source{[Id="Workspaces"]}[Data],
				    #"b1189a55-d3ea-4ceb-8dd9-994de230fca3" = Workspaces{[workspaceId="b1189a55-d3ea-4ceb-8dd9-994de230fca3"]}[Data],
				    #"72d38d67-1c11-412c-98df-4ebbd50bcc7b" = #"b1189a55-d3ea-4ceb-8dd9-994de230fca3"{[dataflowId="72d38d67-1c11-412c-98df-4ebbd50bcc7b"]}[Data],
				    RelationCapacityGroupsReports_ = #"72d38d67-1c11-412c-98df-4ebbd50bcc7b"{[entity="RelationCapacityGroupsReports",version=""]}[Data],
				    #"Filtered Rows" = Table.SelectRows(RelationCapacityGroupsReports_, each [ReportId] <> null and [ReportId] <> ""),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"reportType", "DatasetId"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns",{{"ReportId", "ArtifactId"}, {"ReportName", "ArtifactName"}, {"CapacityNameOfReport", "CapacityName"}}),
				    #"Appended Query" = Table.Combine({#"Renamed Columns1", RelationCapacityGroupsDashboards})
				in
				    #"Appended Query"

	annotation PBI_ResultType = Table

