table DashboardDetails(Excel)
	lineageTag: 7dd0a1d4-e55b-45ea-a547-2973bcc8d0ff

	column DashboardID
		dataType: string
		lineageTag: b5723d96-4579-4116-9e4d-ec013a63893f
		summarizeBy: none
		sourceColumn: DashboardID

		annotation SummarizationSetBy = Automatic

	column DashboardName
		dataType: string
		lineageTag: f7ee5826-7d29-4a56-906f-341497dc0f05
		summarizeBy: none
		sourceColumn: DashboardName

		annotation SummarizationSetBy = Automatic

	column Running
		dataType: int64
		formatString: 0
		lineageTag: c5528d66-f21f-44e1-a437-bf33d71e6443
		summarizeBy: sum
		sourceColumn: Running

		annotation SummarizationSetBy = Automatic

	partition DashboardDetails(Excel)-963dd61d-5927-4eb6-a58b-96cc797f1ab9 = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/PBI%20Reports/Power%20BI%20-%20Info/Subscriptions/PowerBIDashboardEmailSubscriptions.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DashboardID", type text}, {"DashboardName", type text}, {"Running", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

