table DashboardEmailSubscriptionsCreated
	lineageTag: 2827bbbc-e266-4432-ba29-e61fa697fa04

	column activity
		dataType: string
		lineageTag: af34bd0c-c63f-4bcb-a702-d527945480f5
		summarizeBy: none
		sourceColumn: activity

		annotation SummarizationSetBy = Automatic

	column activityid
		dataType: string
		lineageTag: 08bddc81-024f-4669-9c73-5b328d0b50d7
		summarizeBy: none
		sourceColumn: activityid

		annotation SummarizationSetBy = Automatic

	column aggregatedworkspaceinformation
		dataType: string
		lineageTag: 69c04237-58c9-4501-8467-f795750e1dff
		summarizeBy: none
		sourceColumn: aggregatedworkspaceinformation

		annotation SummarizationSetBy = Automatic

	column appname
		dataType: string
		lineageTag: 0c258c35-198c-47fb-ae90-9f11325e0b3c
		summarizeBy: none
		sourceColumn: appname

		annotation SummarizationSetBy = Automatic

	column appreportid
		dataType: string
		lineageTag: a1180158-329a-4512-b950-c09a9bc71424
		summarizeBy: none
		sourceColumn: appreportid

		annotation SummarizationSetBy = Automatic

	column artifactid
		dataType: string
		lineageTag: 6c564e67-f0a4-4727-a325-31716c6232d2
		summarizeBy: none
		sourceColumn: artifactid

		annotation SummarizationSetBy = Automatic

	column artifactname
		dataType: string
		lineageTag: eafd791b-1fc8-4a15-87ac-4a99e2270234
		summarizeBy: none
		sourceColumn: artifactname

		annotation SummarizationSetBy = Automatic

	column artifactobjectid
		dataType: string
		lineageTag: b9913914-e3a0-44e9-bf09-7d8598d92132
		summarizeBy: none
		sourceColumn: artifactobjectid

		annotation SummarizationSetBy = Automatic

	column capacityid
		dataType: string
		lineageTag: 19802449-4f36-47c1-9ecf-a6b8a66192d1
		summarizeBy: none
		sourceColumn: capacityid

		annotation SummarizationSetBy = Automatic

	column capacityname
		dataType: string
		lineageTag: 884baf81-2ea2-407c-85f5-0b22e26526d7
		summarizeBy: none
		sourceColumn: capacityname

		annotation SummarizationSetBy = Automatic

	column clientip
		dataType: string
		lineageTag: 2e24becb-fb9b-4f80-98a3-53503a4bc00e
		summarizeBy: none
		sourceColumn: clientip

		annotation SummarizationSetBy = Automatic

	column consumptionmethod
		dataType: string
		lineageTag: 937136bf-6ba9-42b8-bfe3-a13aaa2cde9a
		summarizeBy: none
		sourceColumn: consumptionmethod

		annotation SummarizationSetBy = Automatic

	column creationtime
		dataType: dateTime
		formatString: General Date
		lineageTag: bd6c6883-be5d-4111-ae03-99d025dda536
		summarizeBy: none
		sourceColumn: creationtime

		annotation SummarizationSetBy = Automatic

	column customvisualaccesstokenresourceid
		dataType: string
		lineageTag: 1ec0edf8-696e-43b4-8e2b-d84c4ab91e15
		summarizeBy: none
		sourceColumn: customvisualaccesstokenresourceid

		annotation SummarizationSetBy = Automatic

	column customvisualaccesstokensiteuri
		dataType: string
		lineageTag: 4974d2c4-765d-4aee-894b-c752b72e8933
		summarizeBy: none
		sourceColumn: customvisualaccesstokensiteuri

		annotation SummarizationSetBy = Automatic

	column dashboardid
		dataType: string
		lineageTag: 9a7a84b4-28c2-4f7b-b6e8-aae34ff69b09
		summarizeBy: none
		sourceColumn: dashboardid

		annotation SummarizationSetBy = Automatic

	column dashboardname
		dataType: string
		lineageTag: 0b5267a1-93aa-4965-86cb-0650681628d5
		summarizeBy: none
		sourceColumn: dashboardname

		annotation SummarizationSetBy = Automatic

	column dataconnectivitymode
		dataType: string
		lineageTag: fade5e00-534d-4758-93de-cc4a2e73f877
		summarizeBy: none
		sourceColumn: dataconnectivitymode

		annotation SummarizationSetBy = Automatic

	column dataflowaccesstokenrequestparameters
		dataType: string
		lineageTag: 2f3a7be0-f95b-47ff-887b-74e78adea351
		summarizeBy: none
		sourceColumn: dataflowaccesstokenrequestparameters

		annotation SummarizationSetBy = Automatic

	column dataflowallownativequeries
		dataType: string
		lineageTag: 95757792-6a98-4a00-a4df-0f35c7301c40
		summarizeBy: none
		sourceColumn: dataflowallownativequeries

		annotation SummarizationSetBy = Automatic

	column dataflowid
		dataType: string
		lineageTag: f28ad9e2-3960-42b3-a152-75c0ca87a00b
		summarizeBy: none
		sourceColumn: dataflowid

		annotation SummarizationSetBy = Automatic

	column dataflowname
		dataType: string
		lineageTag: d41b7356-397e-4af0-bc22-27b70f1ae19e
		summarizeBy: none
		sourceColumn: dataflowname

		annotation SummarizationSetBy = Automatic

	column dataflowrefreshscheduletype
		dataType: string
		lineageTag: beca75c1-ed48-4571-8b7b-9a4f76c2cfff
		summarizeBy: none
		sourceColumn: dataflowrefreshscheduletype

		annotation SummarizationSetBy = Automatic

	column dataflowtype
		dataType: string
		lineageTag: 9910d558-8748-4ce1-b998-56afff2e7ba8
		summarizeBy: none
		sourceColumn: dataflowtype

		annotation SummarizationSetBy = Automatic

	column datasetid
		dataType: string
		lineageTag: 56cb095a-809a-4264-a15b-4374852a8c64
		summarizeBy: none
		sourceColumn: datasetid

		annotation SummarizationSetBy = Automatic

	column datasetname
		dataType: string
		lineageTag: c90d58e0-5d1c-4d32-b029-dd0483c7252e
		summarizeBy: none
		sourceColumn: datasetname

		annotation SummarizationSetBy = Automatic

	column datasets
		dataType: string
		lineageTag: 3978fa91-1448-4dcf-aeb9-3aafa578cc0b
		summarizeBy: none
		sourceColumn: datasets

		annotation SummarizationSetBy = Automatic

	column datasourceid
		dataType: string
		lineageTag: e1a7a610-d68c-4a14-9c4b-dc976c21e491
		summarizeBy: none
		sourceColumn: datasourceid

		annotation SummarizationSetBy = Automatic

	column datasourceobjectids
		dataType: string
		lineageTag: e7b0fef5-dd87-472b-829d-49bc02afd723
		summarizeBy: none
		sourceColumn: datasourceobjectids

		annotation SummarizationSetBy = Automatic

	column distributionmethod
		dataType: string
		lineageTag: 5362f3d7-6903-4d60-b4f8-86407e92e87c
		summarizeBy: none
		sourceColumn: distributionmethod

		annotation SummarizationSetBy = Automatic

	column embedtokenid
		dataType: string
		lineageTag: f835e290-2aa0-4bb3-ae0b-66228438db12
		summarizeBy: none
		sourceColumn: embedtokenid

		annotation SummarizationSetBy = Automatic

	column exporteventenddatetimeparameter
		dataType: string
		lineageTag: c9ec5eb1-7137-4e78-927e-d9be5d19a2be
		summarizeBy: none
		sourceColumn: exporteventenddatetimeparameter

		annotation SummarizationSetBy = Automatic

	column exporteventstartdatetimeparameter
		dataType: string
		lineageTag: c3f594f2-7f10-4742-b89c-51517d92ab91
		summarizeBy: none
		sourceColumn: exporteventstartdatetimeparameter

		annotation SummarizationSetBy = Automatic

	column exportedartifactinfo
		dataType: string
		lineageTag: 28d150b7-9590-4284-a24b-78985d5ebdaf
		summarizeBy: none
		sourceColumn: exportedartifactinfo

		annotation SummarizationSetBy = Automatic

	column externalsubscribeeinformation
		dataType: string
		lineageTag: 44f8a03c-6efa-4847-8797-d3eaa476a789
		summarizeBy: none
		sourceColumn: externalsubscribeeinformation

		annotation SummarizationSetBy = Automatic

	column folderaccessrequests
		dataType: string
		lineageTag: 848dc3ce-cf9a-4e53-a0cf-a3f372eadaa6
		summarizeBy: none
		sourceColumn: folderaccessrequests

		annotation SummarizationSetBy = Automatic

	column folderdisplayname
		dataType: string
		lineageTag: 5213424e-996a-48a3-ad7b-0c1bdcc0a71b
		summarizeBy: none
		sourceColumn: folderdisplayname

		annotation SummarizationSetBy = Automatic

	column folderobjectid
		dataType: string
		lineageTag: 764fd401-8298-479a-9e86-16296d94e953
		summarizeBy: none
		sourceColumn: folderobjectid

		annotation SummarizationSetBy = Automatic

	column gatewayclusterid
		dataType: string
		lineageTag: 039b8183-0817-4bc0-9bbd-bea0326d1796
		summarizeBy: none
		sourceColumn: gatewayclusterid

		annotation SummarizationSetBy = Automatic

	column gatewayid
		dataType: string
		lineageTag: 9893dab9-a889-48ff-b414-db0b9f1f21e6
		summarizeBy: none
		sourceColumn: gatewayid

		annotation SummarizationSetBy = Automatic

	column gatewaymemberid
		dataType: string
		lineageTag: 62316f97-3222-44dc-8ae9-44362e114c55
		summarizeBy: none
		sourceColumn: gatewaymemberid

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: 4549ad1d-ddb9-4b74-8739-38e4696c13fc
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column importdisplayname
		dataType: string
		lineageTag: 6c6aee4e-bee5-49e8-8e4d-43b7bbada944
		summarizeBy: none
		sourceColumn: importdisplayname

		annotation SummarizationSetBy = Automatic

	column importid
		dataType: string
		lineageTag: 5f44f84f-0ab1-4cbc-b860-3d864dea3ad3
		summarizeBy: none
		sourceColumn: importid

		annotation SummarizationSetBy = Automatic

	column importsource
		dataType: string
		lineageTag: 25748eec-38e8-4380-8c52-ef4970ecddc1
		summarizeBy: none
		sourceColumn: importsource

		annotation SummarizationSetBy = Automatic

	column importtype
		dataType: string
		lineageTag: 0c30592a-dc33-488b-bd47-bc828d15651d
		summarizeBy: none
		sourceColumn: importtype

		annotation SummarizationSetBy = Automatic

	column installteamsanalyticsinformation
		dataType: string
		lineageTag: b8e598c2-d6d2-4765-a2f2-b36248e18745
		summarizeBy: none
		sourceColumn: installteamsanalyticsinformation

		annotation SummarizationSetBy = Automatic

	column issuccess
		dataType: string
		lineageTag: 1245d57f-27bd-4bea-a345-573a7be19025
		summarizeBy: none
		sourceColumn: issuccess

		annotation SummarizationSetBy = Automatic

	column istenantadminapi
		dataType: string
		lineageTag: 8b0874c1-7128-4e0f-bdc0-6ef67d3bd337
		summarizeBy: none
		sourceColumn: istenantadminapi

		annotation SummarizationSetBy = Automatic

	column itemname
		dataType: string
		lineageTag: 0fb47bdf-f2dd-4741-9e22-643c808694e8
		summarizeBy: none
		sourceColumn: itemname

		annotation SummarizationSetBy = Automatic

	column lastrefreshtime
		dataType: string
		lineageTag: a80fa591-5a98-458a-99d1-bb381c1dd7f0
		summarizeBy: none
		sourceColumn: lastrefreshtime

		annotation SummarizationSetBy = Automatic

	column modelid
		dataType: string
		lineageTag: 6b775a8f-5770-487f-b65c-29673d1e0623
		summarizeBy: none
		sourceColumn: modelid

		annotation SummarizationSetBy = Automatic

	column modelssnapshots
		dataType: string
		lineageTag: 5ffe698e-3f87-4b03-827d-e843485e6216
		summarizeBy: none
		sourceColumn: modelssnapshots

		annotation SummarizationSetBy = Automatic

	column monikers
		dataType: string
		lineageTag: 757a1be0-78ae-45cd-8cb0-546f14fe6949
		summarizeBy: none
		sourceColumn: monikers

		annotation SummarizationSetBy = Automatic

	column objectid
		dataType: string
		lineageTag: 802d3b05-d6b9-4c77-9d6f-0fd3882550d0
		summarizeBy: none
		sourceColumn: objectid

		annotation SummarizationSetBy = Automatic

	column operation
		dataType: string
		lineageTag: 7d24c77a-e993-4241-bb45-bedc831c7aed
		summarizeBy: none
		sourceColumn: operation

		annotation SummarizationSetBy = Automatic

	column orgapppermission
		dataType: string
		lineageTag: 05fc3392-5400-4ea6-b0db-2404006484f5
		summarizeBy: none
		sourceColumn: orgapppermission

		annotation SummarizationSetBy = Automatic

	column organizationid
		dataType: string
		lineageTag: 8949eb44-443f-4099-ac6b-f6ec268bbb45
		summarizeBy: none
		sourceColumn: organizationid

		annotation SummarizationSetBy = Automatic

	column recordtype
		dataType: string
		lineageTag: 0f908974-bc13-486e-bc86-3c10e2417fd4
		summarizeBy: none
		sourceColumn: recordtype

		annotation SummarizationSetBy = Automatic

	column refreshtype
		dataType: string
		lineageTag: 559ec180-e2b1-4962-bab0-980797326028
		summarizeBy: none
		sourceColumn: refreshtype

		annotation SummarizationSetBy = Automatic

	column reportid
		dataType: string
		lineageTag: 46fb2cf8-e14c-40ed-ab4c-aadb245f844d
		summarizeBy: none
		sourceColumn: reportid

		annotation SummarizationSetBy = Automatic

	column reportname
		dataType: string
		lineageTag: 72543e3c-0427-4cb3-9b0f-993db8374c86
		summarizeBy: none
		sourceColumn: reportname

		annotation SummarizationSetBy = Automatic

	column reporttype
		dataType: string
		lineageTag: 70cfb4b7-bc70-441a-9f9a-5ffdacea0fd6
		summarizeBy: none
		sourceColumn: reporttype

		annotation SummarizationSetBy = Automatic

	column requestid
		dataType: string
		lineageTag: d2a11f43-a1fd-46bf-bd0a-162a64818fa9
		summarizeBy: none
		sourceColumn: requestid

		annotation SummarizationSetBy = Automatic

	column schedules
		dataType: string
		lineageTag: 50135ecc-bfb5-4ca1-a83e-ac9d34093e0f
		summarizeBy: none
		sourceColumn: schedules

		annotation SummarizationSetBy = Automatic

	column sharelinkid
		dataType: string
		lineageTag: 2148c660-6487-48a1-a427-ee705644dfc3
		summarizeBy: none
		sourceColumn: sharelinkid

		annotation SummarizationSetBy = Automatic

	column sharingaction
		dataType: string
		lineageTag: 81a97de9-5a57-4d71-9b73-85e3053f7ceb
		summarizeBy: none
		sourceColumn: sharingaction

		annotation SummarizationSetBy = Automatic

	column sharinginformation
		dataType: string
		lineageTag: 73564163-2ebe-428b-869a-f05dbe0dd2b5
		summarizeBy: none
		sourceColumn: sharinginformation

		annotation SummarizationSetBy = Automatic

	column subscribeeinformation
		dataType: string
		lineageTag: e1f0a679-fc55-4466-835d-98734dd2ed0b
		summarizeBy: none
		sourceColumn: subscribeeinformation

		annotation SummarizationSetBy = Automatic

	column subscriptionschedule
		dataType: string
		lineageTag: 0b6a998c-4ee6-414d-b883-6b5028060a7e
		summarizeBy: none
		sourceColumn: subscriptionschedule

		annotation SummarizationSetBy = Automatic

	column updatefeaturedtables
		dataType: string
		lineageTag: 55acdcae-1663-4baa-91ee-31db9e770363
		summarizeBy: none
		sourceColumn: updatefeaturedtables

		annotation SummarizationSetBy = Automatic

	column useragent
		dataType: string
		lineageTag: dd2f0a3b-c66f-4a8b-8b22-9482ae08ec6b
		summarizeBy: none
		sourceColumn: useragent

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 63e4469c-44b8-4b98-872f-16b3dc0b62f6
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column userkey
		dataType: string
		lineageTag: 43b42e18-398d-4b5f-a8b3-48b4382d55b9
		summarizeBy: none
		sourceColumn: userkey

		annotation SummarizationSetBy = Automatic

	column usertype
		dataType: string
		lineageTag: de888528-549c-4d34-8d99-a4ac35abab58
		summarizeBy: none
		sourceColumn: usertype

		annotation SummarizationSetBy = Automatic

	column workspacename
		dataType: string
		lineageTag: 7bd8c617-858e-4e49-bb6e-1c36aa7edef5
		summarizeBy: none
		sourceColumn: workspacename

		annotation SummarizationSetBy = Automatic

	column workload
		dataType: string
		lineageTag: c7c830b8-fd82-41c5-806f-a769fa3ad066
		summarizeBy: none
		sourceColumn: workload

		annotation SummarizationSetBy = Automatic

	column workspaceid
		dataType: string
		lineageTag: d8c89107-63ca-4597-8cd1-6d5f96c651fd
		summarizeBy: none
		sourceColumn: workspaceid

		annotation SummarizationSetBy = Automatic

	column loaddatenumber
		dataType: int64
		formatString: 0
		lineageTag: 50fb9f05-4762-4187-8dfc-7af92b47352f
		summarizeBy: sum
		sourceColumn: loaddatenumber

		annotation SummarizationSetBy = Automatic

	column CreationDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0750a0ef-be84-4538-85f5-9a8105e629b5
		summarizeBy: none
		sourceColumn: CreationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CreationTime 2'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 9b6f0b80-6189-4a18-bfec-6af5fa17372d
		summarizeBy: none
		sourceColumn: CreationTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Artifact ID'
		dataType: string
		lineageTag: 4569163b-7d19-4251-9e3f-b7390817cbb8
		summarizeBy: none
		sourceColumn: Artifact ID

		annotation SummarizationSetBy = Automatic

	column 'Artifact Name'
		dataType: string
		lineageTag: dfbb38bb-f4d5-4573-ac8c-46970272f623
		summarizeBy: none
		sourceColumn: Artifact Name

		annotation SummarizationSetBy = Automatic

	column 'Artifact Type'
		dataType: string
		lineageTag: 81832365-fd91-425d-88d0-9b0c38b1936f
		summarizeBy: none
		sourceColumn: Artifact Type

		annotation SummarizationSetBy = Automatic

	column 'License Flag'
		dataType: string
		lineageTag: 3f4ff614-d103-48ef-ab85-02c29a0ae5e1
		summarizeBy: none
		sourceColumn: License Flag

		annotation SummarizationSetBy = Automatic

	column dl_insert_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 8ea9d382-5127-4a98-af65-71a313684c08
		summarizeBy: none
		sourceColumn: dl_insert_ts

		annotation SummarizationSetBy = Automatic

	column dl_update_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 817df273-6685-411a-94ff-385d52b84373
		summarizeBy: none
		sourceColumn: dl_update_ts

		annotation SummarizationSetBy = Automatic

	partition DashboardEmailSubscriptionsCreated-98b35baf-bc63-4d2a-aeca-7787454cd97d = m
		mode: import
		source = ```
				let
				    Source=Value.NativeQuery(Snowflake.Databases(ServerName,WarehouseName,[Role=RoleName]){[Name=DatabaseName]}[Data],  
				    "select * from EDLRETAILVIEWSBI.pbi_activityevents where activity in ('CreateEmailSubscription')", null, [EnableFolding=true]),
				    LowercaseColumnNames = Table.TransformColumnNames(Source, Text.Lower),
				    #"Changed Type" = Table.TransformColumnTypes(LowercaseColumnNames,{{"creationtime", type datetime}}),
				    #"Inserted Date" = Table.AddColumn(#"Changed Type", "CreationDate", each DateTime.Date([creationtime]), type date),
				    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "CreationTime", each DateTime.Time([creationtime]), type time),
				    #"Added Custom" = Table.AddColumn(#"Inserted Time", "Artifact ID", each if [reportid] = "" and [dashboardid] <> "" then [dashboardid] else [reportid]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Artifact Name", each if [reportname] = "" and [dashboardname] <> "" then [dashboardname] else [reportname]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Artifact Type", each if [reporttype] = "" and [dashboardid] <> "" then "Dashboard" else [reporttype]),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "License Flag", each if Text.Contains([workspacename],"Personal") or Text.Contains([workspacename],"My Workspace") then "Personal Workspace" else if not Text.Contains([workspacename], "Personal") and [capacityname] = "" and [workspacename] <> "" then "Pro" else if [workspacename] <> "" then "Premium" else ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([Artifact Type] = "Dashboard")),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows1", {"dashboardid"}, #"DashboardDetails(Excel)", {"DashboardID"}, "CreatedSubscriptionsByDashboard", JoinKind.LeftAnti)
				in
				    #"Merged Queries"
				```

	annotation PBI_ResultType = Table

