table pbi_activityevents
	lineageTag: e2c74c30-05be-41b2-96b5-aa107eaad2bb

	column activity
		dataType: string
		lineageTag: f5a654e0-bd36-4322-a09e-5c142e33cc23
		summarizeBy: none
		sourceColumn: activity

		annotation SummarizationSetBy = Automatic

	column activityid
		dataType: string
		lineageTag: 39fa3ba5-9325-4724-ac6d-5f346bf8efc2
		summarizeBy: none
		sourceColumn: activityid

		annotation SummarizationSetBy = Automatic

	column aggregatedworkspaceinformation
		dataType: string
		lineageTag: 2da18521-dc09-433d-b668-bb61f9f6c10c
		summarizeBy: none
		sourceColumn: aggregatedworkspaceinformation

		annotation SummarizationSetBy = Automatic

	column appname
		dataType: string
		lineageTag: 26a474ae-657b-4c48-9693-d5cdae3e420a
		summarizeBy: none
		sourceColumn: appname

		annotation SummarizationSetBy = Automatic

	column appreportid
		dataType: string
		lineageTag: fe6479ab-f6cd-4cb5-92bd-df8fc7ada81e
		summarizeBy: none
		sourceColumn: appreportid

		annotation SummarizationSetBy = Automatic

	column artifactid
		dataType: string
		lineageTag: 48af28a7-ca7c-400e-9d96-1a893d13db97
		summarizeBy: none
		sourceColumn: artifactid

		annotation SummarizationSetBy = Automatic

	column artifactname
		dataType: string
		lineageTag: 8f511549-cd8c-4d79-b42f-d5d4bc059bf0
		summarizeBy: none
		sourceColumn: artifactname

		annotation SummarizationSetBy = Automatic

	column artifactobjectid
		dataType: string
		lineageTag: c01f9959-b10d-4d79-a199-eff50b14a370
		summarizeBy: none
		sourceColumn: artifactobjectid

		annotation SummarizationSetBy = Automatic

	column capacityid
		dataType: string
		lineageTag: 84bae638-93ac-4474-bbb3-afdfa01ab34f
		summarizeBy: none
		sourceColumn: capacityid

		annotation SummarizationSetBy = Automatic

	column capacityname
		dataType: string
		lineageTag: 746c1e1f-e705-417c-a27a-884cea4b9547
		summarizeBy: none
		sourceColumn: capacityname

		annotation SummarizationSetBy = Automatic

	column clientip
		dataType: string
		lineageTag: 1f8764cd-430b-4f5e-80e5-03d1559746cf
		summarizeBy: none
		sourceColumn: clientip

		annotation SummarizationSetBy = Automatic

	column consumptionmethod
		dataType: string
		lineageTag: 70903f8c-e112-4f06-9805-4c1d4a99cc7b
		summarizeBy: none
		sourceColumn: consumptionmethod

		annotation SummarizationSetBy = Automatic

	column creationtime
		dataType: dateTime
		formatString: General Date
		lineageTag: 036f1ce5-cf83-47c8-9105-7236ffc3e574
		summarizeBy: none
		sourceColumn: creationtime

		annotation SummarizationSetBy = Automatic

	column customvisualaccesstokenresourceid
		dataType: string
		lineageTag: 2e969517-da88-4201-a818-a80246cd07be
		summarizeBy: none
		sourceColumn: customvisualaccesstokenresourceid

		annotation SummarizationSetBy = Automatic

	column customvisualaccesstokensiteuri
		dataType: string
		lineageTag: 3e423e30-9c21-4722-82a4-ab156aba0ca5
		summarizeBy: none
		sourceColumn: customvisualaccesstokensiteuri

		annotation SummarizationSetBy = Automatic

	column dashboardid
		dataType: string
		lineageTag: 5e6be05f-924a-4da9-bb59-6bc05d0288fb
		summarizeBy: none
		sourceColumn: dashboardid

		annotation SummarizationSetBy = Automatic

	column dashboardname
		dataType: string
		lineageTag: 74481e58-9c9b-4314-b9fa-045df00d947e
		summarizeBy: none
		sourceColumn: dashboardname

		annotation SummarizationSetBy = Automatic

	column dataconnectivitymode
		dataType: string
		lineageTag: 1be22909-068e-49d8-b53e-075f150e0eb5
		summarizeBy: none
		sourceColumn: dataconnectivitymode

		annotation SummarizationSetBy = Automatic

	column dataflowaccesstokenrequestparameters
		dataType: string
		lineageTag: 77c08573-acd1-432d-91e3-6117f0b9f414
		summarizeBy: none
		sourceColumn: dataflowaccesstokenrequestparameters

		annotation SummarizationSetBy = Automatic

	column dataflowallownativequeries
		dataType: string
		lineageTag: 6a9defc1-382e-496e-a81d-688d5342af46
		summarizeBy: none
		sourceColumn: dataflowallownativequeries

		annotation SummarizationSetBy = Automatic

	column dataflowid
		dataType: string
		lineageTag: a2b86190-8bcc-464d-9222-e9a53a3076cc
		summarizeBy: none
		sourceColumn: dataflowid

		annotation SummarizationSetBy = Automatic

	column dataflowname
		dataType: string
		lineageTag: 8f288ae7-5e89-4654-8f72-83355b1a7335
		summarizeBy: none
		sourceColumn: dataflowname

		annotation SummarizationSetBy = Automatic

	column dataflowrefreshscheduletype
		dataType: string
		lineageTag: da3d28ad-5845-49cf-b904-e3fac869adea
		summarizeBy: none
		sourceColumn: dataflowrefreshscheduletype

		annotation SummarizationSetBy = Automatic

	column dataflowtype
		dataType: string
		lineageTag: e5d3d633-1725-440c-98e6-2f6d2cad426e
		summarizeBy: none
		sourceColumn: dataflowtype

		annotation SummarizationSetBy = Automatic

	column datasetid
		dataType: string
		lineageTag: ec67d1d8-8a72-4e40-bc60-b45c89d31853
		summarizeBy: none
		sourceColumn: datasetid

		annotation SummarizationSetBy = Automatic

	column datasetname
		dataType: string
		lineageTag: a3542df0-cd00-4850-93f4-06a8c61ec29b
		summarizeBy: none
		sourceColumn: datasetname

		annotation SummarizationSetBy = Automatic

	column datasets
		dataType: string
		lineageTag: dad2e7f6-0f1b-41fe-bfa5-5edac61f178c
		summarizeBy: none
		sourceColumn: datasets

		annotation SummarizationSetBy = Automatic

	column datasourceid
		dataType: string
		lineageTag: b130bacd-cb9f-4790-8bdb-52838aaa44a3
		summarizeBy: none
		sourceColumn: datasourceid

		annotation SummarizationSetBy = Automatic

	column datasourceobjectids
		dataType: string
		lineageTag: ab27ac7f-f8fe-4628-a4b3-d6ba4f0ffff3
		summarizeBy: none
		sourceColumn: datasourceobjectids

		annotation SummarizationSetBy = Automatic

	column distributionmethod
		dataType: string
		lineageTag: 4fd7e2c5-5bb6-4a2f-9873-ae88bf2b7192
		summarizeBy: none
		sourceColumn: distributionmethod

		annotation SummarizationSetBy = Automatic

	column embedtokenid
		dataType: string
		lineageTag: afe6fb43-603e-456e-b422-965320025948
		summarizeBy: none
		sourceColumn: embedtokenid

		annotation SummarizationSetBy = Automatic

	column exporteventenddatetimeparameter
		dataType: string
		lineageTag: a0981a00-6f92-4928-a5f1-5eb52fbb9f76
		summarizeBy: none
		sourceColumn: exporteventenddatetimeparameter

		annotation SummarizationSetBy = Automatic

	column exporteventstartdatetimeparameter
		dataType: string
		lineageTag: 324801a2-f9f6-4b44-94d7-b3d7af2073c2
		summarizeBy: none
		sourceColumn: exporteventstartdatetimeparameter

		annotation SummarizationSetBy = Automatic

	column exportedartifactinfo
		dataType: string
		lineageTag: e61d44a2-fc75-4fa5-8831-59219fa37e41
		summarizeBy: none
		sourceColumn: exportedartifactinfo

		annotation SummarizationSetBy = Automatic

	column externalsubscribeeinformation
		dataType: string
		lineageTag: b6694d3d-b31e-49b0-989f-b400962c9e47
		summarizeBy: none
		sourceColumn: externalsubscribeeinformation

		annotation SummarizationSetBy = Automatic

	column folderaccessrequests
		dataType: string
		lineageTag: 4ee47b29-a7e0-46f0-bac0-a40cb8109665
		summarizeBy: none
		sourceColumn: folderaccessrequests

		annotation SummarizationSetBy = Automatic

	column folderdisplayname
		dataType: string
		lineageTag: b1111c39-67ac-4028-9c26-c19537bf8806
		summarizeBy: none
		sourceColumn: folderdisplayname

		annotation SummarizationSetBy = Automatic

	column folderobjectid
		dataType: string
		lineageTag: 235d49c6-9580-4a5f-bb91-14156dea2c92
		summarizeBy: none
		sourceColumn: folderobjectid

		annotation SummarizationSetBy = Automatic

	column gatewayclusterid
		dataType: string
		lineageTag: def8deb4-5cd2-487c-bdf9-bb0188b5d9d9
		summarizeBy: none
		sourceColumn: gatewayclusterid

		annotation SummarizationSetBy = Automatic

	column gatewayid
		dataType: string
		lineageTag: 280ae5a3-2d2a-4970-ba8a-8200e1323329
		summarizeBy: none
		sourceColumn: gatewayid

		annotation SummarizationSetBy = Automatic

	column gatewaymemberid
		dataType: string
		lineageTag: c676b3da-e79c-4eb5-9849-cc88ec7ed242
		summarizeBy: none
		sourceColumn: gatewaymemberid

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: d3996157-c953-4b8e-875b-dd1959cb224f
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column importdisplayname
		dataType: string
		lineageTag: 9a898365-0c83-48e0-8cc0-ead39e9bd70b
		summarizeBy: none
		sourceColumn: importdisplayname

		annotation SummarizationSetBy = Automatic

	column importid
		dataType: string
		lineageTag: 135b34fb-8adf-4c33-97aa-208c6e6a7b6a
		summarizeBy: none
		sourceColumn: importid

		annotation SummarizationSetBy = Automatic

	column importsource
		dataType: string
		lineageTag: bdb02569-5055-45b2-8f1c-73b3cd8ca8f2
		summarizeBy: none
		sourceColumn: importsource

		annotation SummarizationSetBy = Automatic

	column importtype
		dataType: string
		lineageTag: 1c527903-74ac-44bb-8cea-13078014692d
		summarizeBy: none
		sourceColumn: importtype

		annotation SummarizationSetBy = Automatic

	column installteamsanalyticsinformation
		dataType: string
		lineageTag: 8bea72f4-9334-4997-80fe-18479dcc3743
		summarizeBy: none
		sourceColumn: installteamsanalyticsinformation

		annotation SummarizationSetBy = Automatic

	column issuccess
		dataType: string
		lineageTag: c711860e-11a5-4782-870b-d7b9e1702adc
		summarizeBy: none
		sourceColumn: issuccess

		annotation SummarizationSetBy = Automatic

	column istenantadminapi
		dataType: string
		lineageTag: 88349774-0bb5-479d-a30d-e02432e75a98
		summarizeBy: none
		sourceColumn: istenantadminapi

		annotation SummarizationSetBy = Automatic

	column itemname
		dataType: string
		lineageTag: 11c527c3-defa-4852-a0fb-6e738165c31a
		summarizeBy: none
		sourceColumn: itemname

		annotation SummarizationSetBy = Automatic

	column lastrefreshtime
		dataType: string
		lineageTag: e9d44889-951c-4ee9-b541-5c47c86b7034
		summarizeBy: none
		sourceColumn: lastrefreshtime

		annotation SummarizationSetBy = Automatic

	column modelid
		dataType: string
		lineageTag: 0d81c5af-cbbc-4459-a0f1-4a958fcefb07
		summarizeBy: none
		sourceColumn: modelid

		annotation SummarizationSetBy = Automatic

	column modelssnapshots
		dataType: string
		lineageTag: 087cd170-e282-4b86-bcb7-7fbb36567e1b
		summarizeBy: none
		sourceColumn: modelssnapshots

		annotation SummarizationSetBy = Automatic

	column monikers
		dataType: string
		lineageTag: aafdadfd-ba36-4a46-bee5-69855e5130a7
		summarizeBy: none
		sourceColumn: monikers

		annotation SummarizationSetBy = Automatic

	column objectid
		dataType: string
		lineageTag: 0887d869-2124-4278-9b11-e6435f8f91f8
		summarizeBy: none
		sourceColumn: objectid

		annotation SummarizationSetBy = Automatic

	column operation
		dataType: string
		lineageTag: 11822d08-5c91-4ab8-ba48-56286e74528e
		summarizeBy: none
		sourceColumn: operation

		annotation SummarizationSetBy = Automatic

	column orgapppermission
		dataType: string
		lineageTag: 8daf15e6-5320-4e00-bef5-802928c9ab1f
		summarizeBy: none
		sourceColumn: orgapppermission

		annotation SummarizationSetBy = Automatic

	column organizationid
		dataType: string
		lineageTag: 956b7bb2-c310-4abe-b4f2-5591726897d1
		summarizeBy: none
		sourceColumn: organizationid

		annotation SummarizationSetBy = Automatic

	column recordtype
		dataType: string
		lineageTag: 77192b1c-a8ab-4cfc-8988-181d33541793
		summarizeBy: none
		sourceColumn: recordtype

		annotation SummarizationSetBy = Automatic

	column refreshtype
		dataType: string
		lineageTag: eba4a6f4-332e-40fa-bc8a-ac5ae6efe1f0
		summarizeBy: none
		sourceColumn: refreshtype

		annotation SummarizationSetBy = Automatic

	column reportid
		dataType: string
		lineageTag: 0bb6f5eb-04d2-49b4-87aa-a6165e59567e
		summarizeBy: none
		sourceColumn: reportid

		annotation SummarizationSetBy = Automatic

	column reportname
		dataType: string
		lineageTag: ab5bdf4f-0857-42cf-8ea5-4de36e97f398
		summarizeBy: none
		sourceColumn: reportname

		annotation SummarizationSetBy = Automatic

	column reporttype
		dataType: string
		lineageTag: 8c08f27b-a36e-4fec-b757-d304212e4418
		summarizeBy: none
		sourceColumn: reporttype

		annotation SummarizationSetBy = Automatic

	column requestid
		dataType: string
		lineageTag: 31378ebc-a942-4373-909c-9faa84294c26
		summarizeBy: none
		sourceColumn: requestid

		annotation SummarizationSetBy = Automatic

	column schedules
		dataType: string
		lineageTag: 2bcda403-5442-4b53-9503-65ac12d1fe45
		summarizeBy: none
		sourceColumn: schedules

		annotation SummarizationSetBy = Automatic

	column sharelinkid
		dataType: string
		lineageTag: fe1874cc-99e9-4aaf-859f-9c507428a293
		summarizeBy: none
		sourceColumn: sharelinkid

		annotation SummarizationSetBy = Automatic

	column sharingaction
		dataType: string
		lineageTag: 31565e5b-3fa9-43da-80b8-4e1c2029fdd3
		summarizeBy: none
		sourceColumn: sharingaction

		annotation SummarizationSetBy = Automatic

	column sharinginformation
		dataType: string
		lineageTag: 52c4d2bd-82b4-420c-ab2e-b0cd6d791127
		summarizeBy: none
		sourceColumn: sharinginformation

		annotation SummarizationSetBy = Automatic

	column subscribeeinformation
		dataType: string
		lineageTag: f224fa4c-4d8c-4dba-9020-7c35acc76931
		summarizeBy: none
		sourceColumn: subscribeeinformation

		annotation SummarizationSetBy = Automatic

	column subscriptionschedule
		dataType: string
		lineageTag: 49c1eb92-fe67-414d-acc9-b571835c1c44
		summarizeBy: none
		sourceColumn: subscriptionschedule

		annotation SummarizationSetBy = Automatic

	column updatefeaturedtables
		dataType: string
		lineageTag: b94249b6-5f2b-4dc2-b13e-77778830bba9
		summarizeBy: none
		sourceColumn: updatefeaturedtables

		annotation SummarizationSetBy = Automatic

	column useragent
		dataType: string
		lineageTag: 328d0f22-6a11-478c-b476-89abb9faeca9
		summarizeBy: none
		sourceColumn: useragent

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: c9a3475c-8e77-4869-ab19-c5726f3ab0ee
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column userkey
		dataType: string
		lineageTag: b243cf32-520e-4ec3-a196-ca84d4250e04
		summarizeBy: none
		sourceColumn: userkey

		annotation SummarizationSetBy = Automatic

	column usertype
		dataType: string
		lineageTag: fa77c43c-2865-43e8-bdb9-9e9f3b37fecb
		summarizeBy: none
		sourceColumn: usertype

		annotation SummarizationSetBy = Automatic

	column workspacename
		dataType: string
		lineageTag: d08f1178-83f0-444b-b706-70bc1f38c7aa
		summarizeBy: none
		sourceColumn: workspacename

		annotation SummarizationSetBy = Automatic

	column workload
		dataType: string
		lineageTag: 65d003a1-aedc-4708-9fac-ecb346382dd7
		summarizeBy: none
		sourceColumn: workload

		annotation SummarizationSetBy = Automatic

	column workspaceid
		dataType: string
		lineageTag: 4623b31d-f173-42ed-969a-15dcb157775f
		summarizeBy: none
		sourceColumn: workspaceid

		annotation SummarizationSetBy = Automatic

	column loaddatenumber
		dataType: int64
		formatString: 0
		lineageTag: 8d58ae51-1cbf-401f-aa59-5c2b8a2ac422
		summarizeBy: sum
		sourceColumn: loaddatenumber

		annotation SummarizationSetBy = Automatic

	column CreationDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b28a8bc4-9b14-46d9-ba87-48431941ddf7
		summarizeBy: none
		sourceColumn: CreationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CreationTime 2'
		dataType: dateTime
		formatString: Long Time
		lineageTag: af57283a-76b2-4436-a9d8-78fdb9644666
		summarizeBy: none
		sourceColumn: CreationTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column WebUrl = "https://app.powerbi.com/groups/" & pbi_activityevents[workspaceid] & "/reports/" & pbi_activityevents[Artifact ID]
		lineageTag: 32955d55-9c20-4276-b3b0-e7701a5c7309
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Artifact ID'
		dataType: string
		lineageTag: bab064b0-0cf8-4bb7-b8a8-2fbd4b2fa776
		summarizeBy: none
		sourceColumn: Artifact ID

		annotation SummarizationSetBy = Automatic

	column 'Artifact Name'
		dataType: string
		lineageTag: 8682ee6b-6123-4d7b-b506-0b57f3d7c717
		summarizeBy: none
		sourceColumn: Artifact Name

		annotation SummarizationSetBy = Automatic

	column 'Artifact Type'
		dataType: string
		lineageTag: 9d2f9825-4086-486f-93b4-c47574c5dd62
		summarizeBy: none
		sourceColumn: Artifact Type

		annotation SummarizationSetBy = Automatic

	column 'License Flag'
		dataType: string
		lineageTag: dd1fe2e3-8437-4cee-99b7-85239de36631
		summarizeBy: none
		sourceColumn: License Flag

		annotation SummarizationSetBy = Automatic

	column dl_insert_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 1b8b614f-d27b-4550-a76b-5645f28fc733
		summarizeBy: none
		sourceColumn: dl_insert_ts

		annotation SummarizationSetBy = Automatic

	column dl_update_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: d85eeb73-4889-43ec-a30b-9ae6ec290c42
		summarizeBy: none
		sourceColumn: dl_update_ts

		annotation SummarizationSetBy = Automatic

	partition pbi_activityevents-89e94e19-5123-4ce5-9409-67fce9ba3f8d = m
		mode: import
		source = ```
				let
				    Source=Value.NativeQuery(Snowflake.Databases(ServerName,WarehouseName,[Role=RoleName]){[Name=DatabaseName]}[Data],  
				    "select * from EDLRETAILVIEWSBI.pbi_activityevents where activity in ('CreateEmailSubscription','DeleteEmailSubscription','GetSubscriptionUsersByReportIdAsAdmin','RunEmailSubscription','TakeOverEmailSubscription','UpdateEmailSubscription')", null, [EnableFolding=true]),
				    LowercaseColumnNames = Table.TransformColumnNames(Source, Text.Lower),
				    #"Changed Type" = Table.TransformColumnTypes(LowercaseColumnNames,{{"creationtime", type datetime}}),
				    #"Inserted Date" = Table.AddColumn(#"Changed Type", "CreationDate", each DateTime.Date([creationtime]), type date),
				    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "CreationTime", each DateTime.Time([creationtime]), type time),
				    #"Added Custom" = Table.AddColumn(#"Inserted Time", "Artifact ID", each if [reportid] = "" and [dashboardid] <> "" then [dashboardid] else [reportid]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Artifact Name", each if [reportname] = "" and [dashboardname] <> "" then [dashboardname] else [reportname]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Artifact Type", each if [reporttype] = "" and [dashboardid] <> "" then "Dashboard" else [reporttype]),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom2",null,"",Replacer.ReplaceValue,{"workspacename"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"",Replacer.ReplaceValue,{"capacityname"}),
				    #"Added Custom3" = Table.AddColumn(#"Replaced Value1", "License Flag", each if Text.Contains([workspacename],"Personal") or Text.Contains([workspacename],"My Workspace") then "Personal Workspace" else if not Text.Contains([workspacename], "Personal") and [capacityname] = "" and [workspacename] <> "" then "Pro" else if [workspacename] <> "" then "Premium" else "")
				in
				    #"Added Custom3"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

