table ReportEmailSubscriptionsCreated
	lineageTag: 27bc4b3b-b855-42db-874a-0387174a5ba7

	column activity
		dataType: string
		lineageTag: 117010fc-e8f5-4e52-9a36-407e91f94913
		summarizeBy: none
		sourceColumn: activity

		annotation SummarizationSetBy = Automatic

	column activityid
		dataType: string
		lineageTag: df037676-947b-413f-98a3-ab4335960ac1
		summarizeBy: none
		sourceColumn: activityid

		annotation SummarizationSetBy = Automatic

	column aggregatedworkspaceinformation
		dataType: string
		lineageTag: 261cb9a7-4a68-4b3f-a232-e4237018b6a7
		summarizeBy: none
		sourceColumn: aggregatedworkspaceinformation

		annotation SummarizationSetBy = Automatic

	column appname
		dataType: string
		lineageTag: b782770d-3923-4bc7-bd2f-340337d9119f
		summarizeBy: none
		sourceColumn: appname

		annotation SummarizationSetBy = Automatic

	column appreportid
		dataType: string
		lineageTag: 060552df-b5ac-4d22-8f9e-97d30ff813ac
		summarizeBy: none
		sourceColumn: appreportid

		annotation SummarizationSetBy = Automatic

	column artifactid
		dataType: string
		lineageTag: 174b608c-823a-436e-ad5f-f5c32d97dffa
		summarizeBy: none
		sourceColumn: artifactid

		annotation SummarizationSetBy = Automatic

	column artifactname
		dataType: string
		lineageTag: 66c2a29b-5912-430f-8224-5887b8eedfbb
		summarizeBy: none
		sourceColumn: artifactname

		annotation SummarizationSetBy = Automatic

	column artifactobjectid
		dataType: string
		lineageTag: 2d041d0e-b4a3-4bb0-b701-3786a7d0684a
		summarizeBy: none
		sourceColumn: artifactobjectid

		annotation SummarizationSetBy = Automatic

	column capacityid
		dataType: string
		lineageTag: c1437043-0fd2-4efa-9bf4-8eb278196fb9
		summarizeBy: none
		sourceColumn: capacityid

		annotation SummarizationSetBy = Automatic

	column capacityname
		dataType: string
		lineageTag: 2ebdc8cd-1b25-451c-93fc-c3d04d6d1254
		summarizeBy: none
		sourceColumn: capacityname

		annotation SummarizationSetBy = Automatic

	column clientip
		dataType: string
		lineageTag: 26097483-90f0-4fd6-a051-ab2060c3922f
		summarizeBy: none
		sourceColumn: clientip

		annotation SummarizationSetBy = Automatic

	column consumptionmethod
		dataType: string
		lineageTag: 6dc38855-527f-46b2-b04c-5b6003d6c339
		summarizeBy: none
		sourceColumn: consumptionmethod

		annotation SummarizationSetBy = Automatic

	column creationtime
		dataType: dateTime
		formatString: General Date
		lineageTag: 15671eb3-c4f1-45fc-b73e-ae159500b94c
		summarizeBy: none
		sourceColumn: creationtime

		annotation SummarizationSetBy = Automatic

	column customvisualaccesstokenresourceid
		dataType: string
		lineageTag: dc351493-2c8c-48c2-87f9-01264b897730
		summarizeBy: none
		sourceColumn: customvisualaccesstokenresourceid

		annotation SummarizationSetBy = Automatic

	column customvisualaccesstokensiteuri
		dataType: string
		lineageTag: 554ff768-7b66-441b-a460-6278b6d8d202
		summarizeBy: none
		sourceColumn: customvisualaccesstokensiteuri

		annotation SummarizationSetBy = Automatic

	column dashboardid
		dataType: string
		lineageTag: 5d70a03d-b9b0-4ab6-ac67-3739007ff85e
		summarizeBy: none
		sourceColumn: dashboardid

		annotation SummarizationSetBy = Automatic

	column dashboardname
		dataType: string
		lineageTag: 02ff7fd2-91e4-400f-b183-5d49835f5c53
		summarizeBy: none
		sourceColumn: dashboardname

		annotation SummarizationSetBy = Automatic

	column dataconnectivitymode
		dataType: string
		lineageTag: e539f99c-0bb2-4126-a3e2-70ae2354d1a5
		summarizeBy: none
		sourceColumn: dataconnectivitymode

		annotation SummarizationSetBy = Automatic

	column dataflowaccesstokenrequestparameters
		dataType: string
		lineageTag: 7deacdab-a15e-40a1-92aa-583801b81143
		summarizeBy: none
		sourceColumn: dataflowaccesstokenrequestparameters

		annotation SummarizationSetBy = Automatic

	column dataflowallownativequeries
		dataType: string
		lineageTag: cc1ab103-e344-4d7f-ac7f-088cfa149860
		summarizeBy: none
		sourceColumn: dataflowallownativequeries

		annotation SummarizationSetBy = Automatic

	column dataflowid
		dataType: string
		lineageTag: a7c72066-6bbb-4fd9-9eca-1bb12f38a53e
		summarizeBy: none
		sourceColumn: dataflowid

		annotation SummarizationSetBy = Automatic

	column dataflowname
		dataType: string
		lineageTag: 14b726ef-bfb3-4339-9e18-d7a12c59670d
		summarizeBy: none
		sourceColumn: dataflowname

		annotation SummarizationSetBy = Automatic

	column dataflowrefreshscheduletype
		dataType: string
		lineageTag: e7d970a8-da32-4013-a7e4-f7937de72446
		summarizeBy: none
		sourceColumn: dataflowrefreshscheduletype

		annotation SummarizationSetBy = Automatic

	column dataflowtype
		dataType: string
		lineageTag: 21b58077-5e35-4143-9ccd-0a88075624e1
		summarizeBy: none
		sourceColumn: dataflowtype

		annotation SummarizationSetBy = Automatic

	column datasetid
		dataType: string
		lineageTag: 2412c7f5-0a2d-4631-bb4d-08db2bdf7cd9
		summarizeBy: none
		sourceColumn: datasetid

		annotation SummarizationSetBy = Automatic

	column datasetname
		dataType: string
		lineageTag: 1f6f9424-e19d-4e2c-b632-658c8d817cb4
		summarizeBy: none
		sourceColumn: datasetname

		annotation SummarizationSetBy = Automatic

	column datasets
		dataType: string
		lineageTag: f320573f-ba92-4885-a773-dd009fe62ac9
		summarizeBy: none
		sourceColumn: datasets

		annotation SummarizationSetBy = Automatic

	column datasourceid
		dataType: string
		lineageTag: b25032d4-9524-4dc6-ab57-8d3c92d3a365
		summarizeBy: none
		sourceColumn: datasourceid

		annotation SummarizationSetBy = Automatic

	column datasourceobjectids
		dataType: string
		lineageTag: c7b461b6-8107-4263-9ce4-6cf0eb818420
		summarizeBy: none
		sourceColumn: datasourceobjectids

		annotation SummarizationSetBy = Automatic

	column distributionmethod
		dataType: string
		lineageTag: 6948f909-b974-4399-b940-c108bf932ba9
		summarizeBy: none
		sourceColumn: distributionmethod

		annotation SummarizationSetBy = Automatic

	column embedtokenid
		dataType: string
		lineageTag: 51e0925e-0066-406d-b16f-d5b63fe38fb1
		summarizeBy: none
		sourceColumn: embedtokenid

		annotation SummarizationSetBy = Automatic

	column exporteventenddatetimeparameter
		dataType: string
		lineageTag: 05aad640-cbb7-4bd1-9828-81c298d299da
		summarizeBy: none
		sourceColumn: exporteventenddatetimeparameter

		annotation SummarizationSetBy = Automatic

	column exporteventstartdatetimeparameter
		dataType: string
		lineageTag: 2e38d70f-a35d-4bad-98c3-9ed9c65a371d
		summarizeBy: none
		sourceColumn: exporteventstartdatetimeparameter

		annotation SummarizationSetBy = Automatic

	column exportedartifactinfo
		dataType: string
		lineageTag: 675d7410-19ff-4dab-a2a7-2cfc71624d6a
		summarizeBy: none
		sourceColumn: exportedartifactinfo

		annotation SummarizationSetBy = Automatic

	column externalsubscribeeinformation
		dataType: string
		lineageTag: f034b341-c362-4e71-b6e2-f0fa4e1ece6d
		summarizeBy: none
		sourceColumn: externalsubscribeeinformation

		annotation SummarizationSetBy = Automatic

	column folderaccessrequests
		dataType: string
		lineageTag: 70546e3e-17d3-4c10-b546-dd2bf3c93d20
		summarizeBy: none
		sourceColumn: folderaccessrequests

		annotation SummarizationSetBy = Automatic

	column folderdisplayname
		dataType: string
		lineageTag: c70ddb16-85d8-42a3-96d7-c7b36a21a84a
		summarizeBy: none
		sourceColumn: folderdisplayname

		annotation SummarizationSetBy = Automatic

	column folderobjectid
		dataType: string
		lineageTag: 8de3641e-2a44-4710-b2ed-0e838bd27d43
		summarizeBy: none
		sourceColumn: folderobjectid

		annotation SummarizationSetBy = Automatic

	column gatewayclusterid
		dataType: string
		lineageTag: 85d0b805-9182-49a3-9cb9-03ac4d9833c0
		summarizeBy: none
		sourceColumn: gatewayclusterid

		annotation SummarizationSetBy = Automatic

	column gatewayid
		dataType: string
		lineageTag: 5248fecf-5229-46cf-8e9b-c8a91b44840d
		summarizeBy: none
		sourceColumn: gatewayid

		annotation SummarizationSetBy = Automatic

	column gatewaymemberid
		dataType: string
		lineageTag: 287d746e-cc11-428c-89cb-0c190a846ee2
		summarizeBy: none
		sourceColumn: gatewaymemberid

		annotation SummarizationSetBy = Automatic

	column id
		dataType: string
		lineageTag: 376ddc97-2913-4f57-944a-2ecd6f20166b
		summarizeBy: none
		sourceColumn: id

		annotation SummarizationSetBy = Automatic

	column importdisplayname
		dataType: string
		lineageTag: a58a4914-c111-46eb-8ada-f03a7adb7beb
		summarizeBy: none
		sourceColumn: importdisplayname

		annotation SummarizationSetBy = Automatic

	column importid
		dataType: string
		lineageTag: 0c640a4c-6ed8-4254-b436-53e1b2ac3a59
		summarizeBy: none
		sourceColumn: importid

		annotation SummarizationSetBy = Automatic

	column importsource
		dataType: string
		lineageTag: 1b0ba46d-02cb-4718-bbf5-96613e9f9274
		summarizeBy: none
		sourceColumn: importsource

		annotation SummarizationSetBy = Automatic

	column importtype
		dataType: string
		lineageTag: d24c66d1-076b-4653-8023-7c528ddff13f
		summarizeBy: none
		sourceColumn: importtype

		annotation SummarizationSetBy = Automatic

	column installteamsanalyticsinformation
		dataType: string
		lineageTag: 61e974f6-a274-453d-9621-e902c9d11c82
		summarizeBy: none
		sourceColumn: installteamsanalyticsinformation

		annotation SummarizationSetBy = Automatic

	column issuccess
		dataType: string
		lineageTag: c49b4e2a-87da-4f1d-bd14-21a356dad761
		summarizeBy: none
		sourceColumn: issuccess

		annotation SummarizationSetBy = Automatic

	column istenantadminapi
		dataType: string
		lineageTag: 28953090-97bc-45ce-9dd5-954fd31893e4
		summarizeBy: none
		sourceColumn: istenantadminapi

		annotation SummarizationSetBy = Automatic

	column itemname
		dataType: string
		lineageTag: 5f4747ec-8564-4b5a-a350-bb61ebae9cc3
		summarizeBy: none
		sourceColumn: itemname

		annotation SummarizationSetBy = Automatic

	column lastrefreshtime
		dataType: string
		lineageTag: 938458a2-3689-47c4-86e6-4b2174ab05b9
		summarizeBy: none
		sourceColumn: lastrefreshtime

		annotation SummarizationSetBy = Automatic

	column modelid
		dataType: string
		lineageTag: f3c09afd-0e35-470d-a110-8c5194ba75f4
		summarizeBy: none
		sourceColumn: modelid

		annotation SummarizationSetBy = Automatic

	column modelssnapshots
		dataType: string
		lineageTag: 8bb36b76-6752-45d0-a5c6-e0b5c654c343
		summarizeBy: none
		sourceColumn: modelssnapshots

		annotation SummarizationSetBy = Automatic

	column monikers
		dataType: string
		lineageTag: 0b1b954d-3eff-4ecd-90ed-ee46578483b2
		summarizeBy: none
		sourceColumn: monikers

		annotation SummarizationSetBy = Automatic

	column objectid
		dataType: string
		lineageTag: 01081444-6016-4514-ac53-10eaa52b6446
		summarizeBy: none
		sourceColumn: objectid

		annotation SummarizationSetBy = Automatic

	column operation
		dataType: string
		lineageTag: 9449c428-522c-4c64-9942-7031732c857a
		summarizeBy: none
		sourceColumn: operation

		annotation SummarizationSetBy = Automatic

	column orgapppermission
		dataType: string
		lineageTag: d798d363-cc15-4e2c-b76a-7b06ea6f91cf
		summarizeBy: none
		sourceColumn: orgapppermission

		annotation SummarizationSetBy = Automatic

	column organizationid
		dataType: string
		lineageTag: dcefb013-de7b-443f-a982-175defbf1984
		summarizeBy: none
		sourceColumn: organizationid

		annotation SummarizationSetBy = Automatic

	column recordtype
		dataType: string
		lineageTag: 24a059be-de2f-4f39-91ff-bfa94f68c3a1
		summarizeBy: none
		sourceColumn: recordtype

		annotation SummarizationSetBy = Automatic

	column refreshtype
		dataType: string
		lineageTag: 656d39ec-052d-4fc2-9faa-ce007346198c
		summarizeBy: none
		sourceColumn: refreshtype

		annotation SummarizationSetBy = Automatic

	column reportid
		dataType: string
		lineageTag: a2a2e5e0-d43f-4f47-a0c0-a739b4f70a21
		summarizeBy: none
		sourceColumn: reportid

		annotation SummarizationSetBy = Automatic

	column reportname
		dataType: string
		lineageTag: 1dae0a95-8156-4cfe-a351-eeac701e40f3
		summarizeBy: none
		sourceColumn: reportname

		annotation SummarizationSetBy = Automatic

	column reporttype
		dataType: string
		lineageTag: 2370f8a6-7650-4652-8c79-7077a36013a4
		summarizeBy: none
		sourceColumn: reporttype

		annotation SummarizationSetBy = Automatic

	column requestid
		dataType: string
		lineageTag: f88a02a0-78f7-46d9-ba2f-2ffa3260b2e4
		summarizeBy: none
		sourceColumn: requestid

		annotation SummarizationSetBy = Automatic

	column schedules
		dataType: string
		lineageTag: 7156b976-280a-4fec-8627-7f582a2fb4da
		summarizeBy: none
		sourceColumn: schedules

		annotation SummarizationSetBy = Automatic

	column sharelinkid
		dataType: string
		lineageTag: ba02bc22-b489-4908-abdc-38ab49b562d9
		summarizeBy: none
		sourceColumn: sharelinkid

		annotation SummarizationSetBy = Automatic

	column sharingaction
		dataType: string
		lineageTag: f5742b11-1cbe-4e2f-93fe-0f560c0d48bd
		summarizeBy: none
		sourceColumn: sharingaction

		annotation SummarizationSetBy = Automatic

	column sharinginformation
		dataType: string
		lineageTag: 64a7531c-cf21-400f-9275-6c125a0924ef
		summarizeBy: none
		sourceColumn: sharinginformation

		annotation SummarizationSetBy = Automatic

	column subscribeeinformation
		dataType: string
		lineageTag: 9f997256-c7e4-41f2-b450-c7073fa0f790
		summarizeBy: none
		sourceColumn: subscribeeinformation

		annotation SummarizationSetBy = Automatic

	column subscriptionschedule
		dataType: string
		lineageTag: 5017312e-37b5-45da-a253-7d5225ad9fe1
		summarizeBy: none
		sourceColumn: subscriptionschedule

		annotation SummarizationSetBy = Automatic

	column updatefeaturedtables
		dataType: string
		lineageTag: 7dd03fab-6da6-4201-8a56-88223d835d52
		summarizeBy: none
		sourceColumn: updatefeaturedtables

		annotation SummarizationSetBy = Automatic

	column useragent
		dataType: string
		lineageTag: 7bd8f51a-7220-4da0-bbc9-d8cf1f3ac6d9
		summarizeBy: none
		sourceColumn: useragent

		annotation SummarizationSetBy = Automatic

	column userid
		dataType: string
		lineageTag: 61326d13-e782-4aec-93ea-b410c583c7c3
		summarizeBy: none
		sourceColumn: userid

		annotation SummarizationSetBy = Automatic

	column userkey
		dataType: string
		lineageTag: 83f2a1e7-bd48-48e5-8edf-b612e33fe714
		summarizeBy: none
		sourceColumn: userkey

		annotation SummarizationSetBy = Automatic

	column usertype
		dataType: string
		lineageTag: d617674a-47b0-451a-b694-dc7e8602c2c1
		summarizeBy: none
		sourceColumn: usertype

		annotation SummarizationSetBy = Automatic

	column workspacename
		dataType: string
		lineageTag: 6e4f5e62-c0c7-4e36-9910-03025666c918
		summarizeBy: none
		sourceColumn: workspacename

		annotation SummarizationSetBy = Automatic

	column workload
		dataType: string
		lineageTag: 1227e13b-9927-4636-bffb-aaac25b76825
		summarizeBy: none
		sourceColumn: workload

		annotation SummarizationSetBy = Automatic

	column workspaceid
		dataType: string
		lineageTag: 7f521247-569e-472a-b54c-f9a0816efe47
		summarizeBy: none
		sourceColumn: workspaceid

		annotation SummarizationSetBy = Automatic

	column loaddatenumber
		dataType: int64
		formatString: 0
		lineageTag: 650a7815-d26f-477d-b8a8-56d85b67c9fe
		summarizeBy: sum
		sourceColumn: loaddatenumber

		annotation SummarizationSetBy = Automatic

	column CreationDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 63c152ad-4239-447b-aebd-9fc4cc377a8f
		summarizeBy: none
		sourceColumn: CreationDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'CreationTime 2'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 59b43e28-3458-4a6a-ace0-69558276379c
		summarizeBy: none
		sourceColumn: CreationTime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Artifact ID'
		dataType: string
		lineageTag: 815d19cc-5111-4f8e-911e-ac94a628dea4
		summarizeBy: none
		sourceColumn: Artifact ID

		annotation SummarizationSetBy = Automatic

	column 'Artifact Name'
		dataType: string
		lineageTag: d374a7a3-07f1-47fa-893c-3b561d4f9ed4
		summarizeBy: none
		sourceColumn: Artifact Name

		annotation SummarizationSetBy = Automatic

	column 'Artifact Type'
		dataType: string
		lineageTag: 94e60074-be3f-4ee3-ac27-154dd5cfd880
		summarizeBy: none
		sourceColumn: Artifact Type

		annotation SummarizationSetBy = Automatic

	column 'License Flag'
		dataType: string
		lineageTag: a9eea788-26ec-4d59-84ba-7c8629f62bc0
		summarizeBy: none
		sourceColumn: License Flag

		annotation SummarizationSetBy = Automatic

	column dl_insert_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 6c3bec75-eca5-429d-93b6-b356f3bd9845
		summarizeBy: none
		sourceColumn: dl_insert_ts

		annotation SummarizationSetBy = Automatic

	column dl_update_ts
		dataType: dateTime
		formatString: General Date
		lineageTag: 7864ef8c-fa83-47ef-b450-c7994ffec5c7
		summarizeBy: none
		sourceColumn: dl_update_ts

		annotation SummarizationSetBy = Automatic

	partition ReportEmailSubscriptionsCreated-95c47d9c-4170-4ef4-9cda-afd445496a95 = m
		mode: import
		source = ```
				let
				    Source=Value.NativeQuery(Snowflake.Databases(ServerName,WarehouseName,[Role=RoleName]){[Name=DatabaseName]}[Data],  
				    "select * from EDLRETAILVIEWSBI.pbi_activityevents where activity in ('CreateEmailSubscription')", null, [EnableFolding=true]),
				    LowercaseColumnNames = Table.TransformColumnNames(Source, Text.Lower),
				    #"Changed Type" = Table.TransformColumnTypes(LowercaseColumnNames,{{"creationtime", type datetime}}),
				    #"Inserted Date" = Table.AddColumn(#"Changed Type", "CreationDate", each DateTime.Date([creationtime]), type date),
				    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "CreationTime", each DateTime.Time([creationtime]), type time),
				    #"Added Custom" = Table.AddColumn(#"Inserted Time", "Artifact ID", each if [reportid] = "" and [dashboardid] <> "" then [dashboardid] else [reportid]),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Artifact Name", each if [reportname] = "" and [dashboardname] <> "" then [dashboardname] else [reportname]),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Artifact Type", each if [reporttype] = "" and [dashboardid] <> "" then "Dashboard" else [reporttype]),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "License Flag", each if Text.Contains([workspacename],"Personal") or Text.Contains([workspacename],"My Workspace") then "Personal Workspace" else if not Text.Contains([workspacename], "Personal") and [capacityname] = "" and [workspacename] <> "" then "Pro" else if [workspacename] <> "" then "Premium" else ""),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([Artifact Type] = "PowerBIReport")),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows1", {"reportid"}, #"ReportDetails(Excel)", {"ReportId"}, "CreatedSubscriptionsByReportId", JoinKind.LeftAnti)
				in
				    #"Merged Queries"
				```

	annotation PBI_ResultType = Table

