table 'ReportsDeleted(MakeRunning - 0)'
	lineageTag: e362c941-8a9e-4205-960c-0a5ec7d52439

	column ReportId
		dataType: string
		lineageTag: 776f32ed-84c4-42be-bec3-9a91930c99cd
		summarizeBy: none
		sourceColumn: ReportId

		annotation SummarizationSetBy = Automatic

	column ReportName
		dataType: string
		lineageTag: 01656dfa-5ea5-4db3-87a0-c08c92ae8430
		summarizeBy: none
		sourceColumn: ReportName

		annotation SummarizationSetBy = Automatic

	column Running
		dataType: int64
		formatString: 0
		lineageTag: bae65c02-fe4c-4d2b-b631-639e23245a9c
		summarizeBy: sum
		sourceColumn: Running

		annotation SummarizationSetBy = Automatic

	partition 'ReportsDeleted(MakeRunning - 0)-990be8c9-a8ac-4aa1-b9e1-9fce923e9cf3' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://coralracing.sharepoint.com/sites/CentralPowerBI/Shared%20Documents/PBI%20Reports/Power%20BI%20-%20Info/Subscriptions/PowerBIReportEmailSubscriptions.xlsx"), null, true),
				    data_Sheet = Source{[Item="data",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(data_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReportId", type text}, {"ReportName", type text}, {"Running", Int64.Type}}),
				    #"Merged Queries" = Table.NestedJoin(#"Changed Type", {"ReportId"}, CreatedSubscriptionsByReportId_API, {"artifactId"}, "CreatedSubscriptionsByReportId_API", JoinKind.LeftAnti),
				    #"Filtered Rows" = Table.SelectRows(#"Merged Queries", each ([Running] = 1))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

