name: Power BI Deployment
on:
  push:
    branches:
      - master # Or your main branch
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Git Credential Manager
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Install Power BI CLI
        run: |
          npm i -g @powerbi-cli/powerbi-cli
      - name: Power BI Login
        run: |
          pbicli login --service-principal --principal "${{ secrets.POWERBI_CLIENT_ID }}" --secret "${{ secrets.POWERBI_CLIENT_SECRET }}" --tenant "${{ secrets.POWERBI_TENANT_ID }}"
      - name: Deploy Power BI Content
        run: |
          pbicli push --file "./CI_CD_Backup" --workspace "5734be30-0851-455e-8b8d-2d1de9201b20" 
          echo "Deploying Power BI content..."
