name: Power BI Deployment
on:
  push:
    branches:
      - master # Or your main branch
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Git Credential Manager
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Install Power BI Shell Module
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber
      - name: Power BI Login
        run: |
          $reportJson = Get-Content -Raw -Path "reports.json" | ConvertFrom-Json
          $tenantId = "${{ secrets.POWERBI_TENANT_ID }}"
          $appId = "${{ secrets.POWERBI_CLIENT_ID }}"
          $appSecret = "${{ secrets.POWERBI_CLIENT_SECRET }}"
          $SecurePassword = ConvertTo-SecureString $appSecret -AsPlainText -Force
          $credentials = New-Object System.Management.Automation.PSCredential($appId, $SecurePassword)
          
          Login-PowerBIServiceAccount -ServicePrincipal -Tenant $tenantId -Credential $credentials
          foreach ($report in $reportJson.reports) {
            $workspaceId = $report.workspaceId
            foreach ($reportName in $report.reportList) {
              New-PowerBIReport -Path ".\CI_CD_Backup\Reports\"+$reportName+".pbix" -WorkspaceId $workspaceId -ConflictAction "CreateOrOverwrite"
            }
          }
