name: Power BI Deployment
on:
  push:
    branches:
      - master # Or your main branch
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Git Credential Manager
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Install Power BI Shell Module
        run: |
          Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber
      - name: Power BI Login
        run: |
          $tenantId = "${{ secrets.POWERBI_TENANT_ID }}"
          $appId = "${{ secrets.POWERBI_CLIENT_ID }}"
          $appSecret = "${{ secrets.POWERBI_CLIENT_SECRET }}"
          $SecurePassword = ConvertTo-SecureString $appSecret -AsPlainText -Force
          $credentials = New-Object System.Management.Automation.PSCredential($appId, $SecurePassword)
          
          Login-PowerBIServiceAccount -ServicePrincipal -Tenant $tenantId -Credential $credentials
      - name: Deploy Power BI Content
        run: |
          New-PowerBIReport -Path "./CI_CD_Backups" -WorkspaceId "5734be30-0851-455e-8b8d-2d1de9201b20" -ConflictAction "CreateOrOverwrite"
